### ISSUE TITLE
running error with the model download from model zoo

### ISSUE THREAD

**Issue by sureone** [facebookresearch/SlowFast#132]
Has anyone have below issue when testing?

**1. running command**
python tools/run_net.py \
  --cfg configs/AVA/c2/SLOWFAST_32x2_R101_50_50_v2.1.yaml \
  TEST.CHECKPOINT_FILE_PATH SLOWFAST_32x2_R101_50_50_v2.1.pkl  \
  TRAIN.ENABLE False \
  TEST.CHECKPOINT_TYPE pytorch

**2. model file**
https://dl.fbaipublicfiles.com/pyslowfast/model_zoo/ava/SLOWFAST_32x2_R101_50_50_v2.1.pkl
and here the md5sum of the file: **a83567b0c40f844fdcce03df1cd21dcc**

**3. running log:**
checkpoint type= pytorch ,model= SLOWFAST_32x2_R101_50_50_v2.1.pkl
Traceback (most recent call last):
  File "tools/run_net.py", line 152, in <module>
    main()
  File "tools/run_net.py", line 147, in main
    test(cfg=cfg)
  File "/home/wcare/slowfast/tools/test_net.py", line 139, in test
    convert_from_caffe2=cfg.TEST.CHECKPOINT_TYPE == "caffe2",
  File "/home/wcare/slowfast/slowfast/utils/checkpoint.py", line 225, in load_checkpoint
    checkpoint = torch.load(path_to_checkpoint, map_location="cpu")
  File "/home/wcare/.local/lib/python3.6/site-packages/torch/serialization.py", line 529, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/wcare/.local/lib/python3.6/site-packages/torch/serialization.py", line 692, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa4 in position 5: invalid start byte

**also I try to load the pkl file with `torch.load("SLOWFAST_32x2_R101_50_50_v2.1.pkl")` simply, got the same error as above.**

**Comment by takatosp1** [comment]
Hi

Thank for playing with PySlowFast!
You could follow the instruction in the Getting started, or you could check #19 to fix the issue.

Thanks
