### ISSUE TITLE
getting issue with the models at modelzoo

### ISSUE THREAD

**Issue by AbhinavJhanwar** [facebookresearch/SlowFast#151]
Python 3.6.9
av==7.0.1
PyWavelets==1.1.1
torch==1.4.0
torchsummary==1.5.1
torchtext==0.3.1
torchvision==0.5.0

using command-
python tools/run_net.py --cfg /content/slowfast/configs/Kinetics/c2/SLOWFAST_8x8_R50.yaml \
  DATA.PATH_TO_DATA_DIR ${test_data}
  TEST.CHECKPOINT_FILE_PATH SLOWFAST_8x8_R50.pkl \
  TEST.CHECKPOINT_TYPE caffe2 \
  NUM_GPUS 1 \
  TRAIN.ENABLE False

Traceback (most recent call last):
  File "tools/run_net.py", line 152, in <module>
    main()
  File "tools/run_net.py", line 147, in main
    test(cfg=cfg)
  File "/content/slowfast/tools/test_net.py", line 139, in test
    convert_from_caffe2=cfg.TEST.CHECKPOINT_TYPE == "caffe2",
  File "/content/slowfast/slowfast/utils/checkpoint.py", line 183, in load_checkpoint
    caffe2_checkpoint = pickle.load(f, encoding="latin1")
_pickle.UnpicklingError: pickle data was truncated

**Comment by AbhinavJhanwar** [comment]
.pkl file was partially downloaded. so downloading it again solved the issue.

**Comment by vermavinay982** [comment]
```py
file = 'SLOWFAST_8x8_R50.pkl'
model = torch.load(file)
print(model)
```
Its giving "cant decode" error.

File "/opt/conda/lib/python3.8/site-packages/torch/serialization.py", line 608, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/opt/conda/lib/python3.8/site-packages/torch/serialization.py", line 777, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd4 in position 1: invalid continuation byte
