### ISSUE TITLE
KeyError: 'blobs'

### ISSUE THREAD

**Issue by pjw-cmd** [facebookresearch/SlowFast#170]
An error occurred when I tried to test slowfast_64x2_r101_50_50.pkl for the pretraining model.It show the following:Traceback (most recent call last):
  File "tools/run_net.py", line 142, in <module>
    main()
  File "tools/run_net.py", line 138, in main
    func(cfg=cfg)
  File "/home/pjw/SlowFast-master1/tools/demo_net.py", line 99, in demo
    convert_from_caffe2= "caffe2" in [cfg.TEST.CHECKPOINT_TYPE, cfg.TRAIN.CHECKPOINT_TYPE],
  File "/home/pjw/SlowFast-master1/slowfast/utils/checkpoint.py", line 189, in load_checkpoint
    for key in caffe2_checkpoint["blobs"].keys():
KeyError: 'blobs'
And in/slowfast/utils/checkpoint. Py directory line 183: caffe2_checkpoint = pickle.load (f, encoding = "latin1"), I print caffe2_checkpoint is a string of Numbers, type is int.It doesn't work, so I'm going to change it to torch. load (f,encoding="latin1",map_location=" cpu "), but it still shows no blobs attribute, so how do I fix it?Thanks!

**Comment by coocoo90** [comment]
@pjw-cmd have solved that problem?
I have the same problem and seems that happens only for the "slowfast_64x2_r101_50_50.pkl"
and the "slowfast_32x2_r101_50_50.pkl".
It only returns an integer value after loading the ".pkl" file using pickle.

**Comment by xxxxy888** [comment]
I have the same error ,have you  solved that problem?
Traceback (most recent call last):
  File "tools/run_net.py", line 52, in <module>
    main()
  File "tools/run_net.py", line 27, in main
    launch_job(cfg=cfg, init_method=args.init_method, func=train)
  File "/home/guide/SlowFast/slowfast/utils/misc.py", line 430, in launch_job
    func(cfg=cfg)
  File "/home/guide/SlowFast/tools/train_net.py", line 579, in train
    checkpoint_epoch = cu.load_checkpoint(
  File "/home/guide/SlowFast/slowfast/utils/checkpoint.py", line 231, in load_checkpoint
    for key in caffe2_checkpoint["blobs"].keys():
KeyError: 'blobs'
