### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd4 in position 1: invalid continuation byte

### ISSUE THREAD

**Issue by hyounsamk** [facebookresearch/SlowFast#21]
When I run "SLOWFAST_8x8_R50" model with the command below, I got "UnicodeDecodeError" error.

I also got 'RuntimeError: Invalid magic number; corrupt file?' when I load the weight file with "bytes" encoding.

## Steps to reproduce
```sh
# version info
$ python --version
Python 3.7.2
$ pip freeze | grep -E "(av|torch)"
av==6.2.0
PyWavelets==1.0.2
torch==1.3.0
torchgeometry==0.1.2
torchvision==0.4.1

$ python tools/run_net.py \
  --cfg configs/Kinetics/c2/SLOWFAST_8x8_R50.yaml \
  DATA.PATH_TO_DATA_DIR ${path_to_test_data} \
  TEST.CHECKPOINT_FILE_PATH ${path_to_model}/SLOWFAST_8x8_R50.pkl \
  TRAIN.ENABLE False \
```
## Observed Results
```sh
Traceback (most recent call last):
  File "tools/run_net.py", line 152, in <module>
    main()
  File "tools/run_net.py", line 148, in main
    test(cfg=cfg)
  File "/home/peterk/Workspace/slowfast/tools/test_net.py", line 102, in test
    convert_from_caffe2=cfg.TEST.CHECKPOINT_TYPE == "caffe2",
  File "/home/peterk/Workspace/slowfast/slowfast/utils/checkpoint.py", line 214, in load_checkpoint
    checkpoint = torch.load(path_to_checkpoint, map_location=torch.device("cpu"))
  File "/home/peterk/.local/anaconda3/envs/e_torch/lib/python3.7/site-packages/torch/serialization.py", line 426, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/home/peterk/.local/anaconda3/envs/e_torch/lib/python3.7/site-packages/torch/serialization.py", line 603, in _load
    magic_number = pickle_module.load(f, **pickle_load_args)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd4 in position 1: invalid continuation byte
```

**Comment by takatosp1** [comment]
Hi
Thanks for using the codebase! 
You might follow the instruction in GETTING_STARTED.md, where you will find you need to set the checkpoint type CHECKPOINT_TYPE to caffe2 when you loading a caffe2 model.

You can also follow the instruction here:
https://github.com/facebookresearch/SlowFast/issues/19

**Comment by hyounsamk** [comment]
Thanks for your support!
The following command does work.

```sh
$ python tools/run_net.py \
  --cfg configs/Kinetics/c2/SLOWFAST_8x8_R50.yaml \
  DATA.PATH_TO_DATA_DIR ${path_to_test_data} \
  TEST.CHECKPOINT_FILE_PATH ${path_to_model}/SLOWFAST_8x8_R50.pkl \
  TRAIN.ENABLE False \
  TEST.CHECKPOINT_TYPE caffe2
```
