### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory:

### ISSUE THREAD

**Issue by 97zhutianhao** [facebookresearch/SlowFast#211]
hello！When I run the following command，An error has occurred
`-- Process 3 terminated with the following error:
Traceback (most recent call last):
  File "/home/zhutianhao/anaconda3/envs/acmmm/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 20, in _wrap
    fn(i, *args)
  File "/home/zhutianhao/acm/SlowFast-master/slowfast/utils/multiprocessing.py", line 50, in run
    func(cfg)
  File "/home/zhutianhao/acm/SlowFast-master/tools/test_net.py", line 187, in test
    perform_test(test_loader, model, test_meter, cfg)
  File "/home/zhutianhao/anaconda3/envs/acmmm/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 15, in decorate_context
    return func(*args, **kwargs)
  File "/home/zhutianhao/acm/SlowFast-master/tools/test_net.py", line 43, in perform_test
    for cur_iter, (inputs, labels, video_idx, meta) in enumerate(test_loader):
  File "/home/zhutianhao/anaconda3/envs/acmmm/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/zhutianhao/anaconda3/envs/acmmm/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/home/zhutianhao/anaconda3/envs/acmmm/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/home/zhutianhao/anaconda3/envs/acmmm/lib/python3.6/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/zhutianhao/anaconda3/envs/acmmm/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/zhutianhao/anaconda3/envs/acmmm/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/zhutianhao/anaconda3/envs/acmmm/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/zhutianhao/acm/SlowFast-master/slowfast/datasets/ava_dataset.py", line 383, in __getitem__
    image_paths, backend=self.cfg.AVA.IMG_PROC_BACKEND
  File "/home/zhutianhao/acm/SlowFast-master/slowfast/datasets/utils.py", line 35, in retry_load_images
    with PathManager.open(image_path, "rb") as f:
  File "/home/zhutianhao/anaconda3/envs/acmmm/lib/python3.6/site-packages/fvcore/common/file_io.py", line 575, in open
    path, mode, buffering=buffering, **kwargs
  File "/home/zhutianhao/anaconda3/envs/acmmm/lib/python3.6/site-packages/fvcore/common/file_io.py", line 380, in _open
    opener=opener,
FileNotFoundError: [Errno 2] No such file or directory: ' /home/zhutianhao/data/ava/val/Ekwy7wzLfjc/Ekwy7wzLfjc_015899.jpg'
`
But I made sure I had it in my directory, and I checked it several times

**Comment by Staniwnl** [comment]
Hi, did you solve this problem? I ran into a similar error.  @97-tianyan
