### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by habatua** [facebookresearch/SlowFast#227]
when I run 
#!/bin/bash
python tools/run_net.py \
    --cfg configs/Kinetics/C2D_8x8_R50.yaml \
    DATA.PATH_TO_DATA_DIR  /home/data2/wangjunying/ActivityNet/Crawler/Kinetics/data/\
    NUM_GPUS 2 \
    TRAIN.BATCH_SIZE 16 \

There is a problem:
-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/home/data2/wangjunying/anaconda3/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 20, in _wrap
    fn(i, *args)
  File "/home/data2/wangjunying/SlowFast-master/slowfast/utils/multiprocessing.py", line 50, in run
    func(cfg)
  File "/home/data2/wangjunying/SlowFast-master/tools/train_net.py", line 381, in train
    train_loader = loader.construct_loader(cfg, "train")
  File "/home/data2/wangjunying/SlowFast-master/slowfast/datasets/loader.py", line 82, in construct_loader
    dataset = build_dataset(dataset_name, cfg, split)
  File "/home/data2/wangjunying/SlowFast-master/slowfast/datasets/build.py", line 31, in build_dataset
    return DATASET_REGISTRY.get(name)(cfg, split)
  File "/home/data2/wangjunying/SlowFast-master/slowfast/datasets/kinetics.py", line 74, in __init__
    self._construct_loader()
  File "/home/data2/wangjunying/SlowFast-master/slowfast/datasets/kinetics.py", line 92, in _construct_loader
    assert len(path_label.split()) == 2
AssertionError

Could you help me with this problem?
Best wishes!

**Comment by ashwinvaswani** [comment]
@habatua I am facing the same problem. How did you fix it?

**Comment by habatua** [comment]
> @habatua I am facing the same problem. How did you fix it?
Hi, the csv file should be: 
        path_to_video_1 label_1
        path_to_video_2 label_2
        ...
        path_to_video_N label_N

**Comment by haooooooqi** [comment]
Hi @habatua 
Thanks for playing with PySlowFast, you might want to find DATA.PATH_LABEL_SEPARATOR and make sure it is the same as what you use in your csv.
Note there are difference between space and tab.

Thanks,
Haoqi

**Comment by Epiphqny** [comment]
@haooooooqi Could you show one-line example of the csv file, I don't know how to use space to separate the items, aren't the csv file separated by comma?
