### ISSUE TITLE
Training starts then RuntimeError on ava dataset.

### ISSUE THREAD

**Issue by thezaza101** [facebookresearch/SlowFast#291]
**To Reproduce**
Followed instructions to [install ](https://github.com/facebookresearch/SlowFast/blob/master/INSTALL.md)and [prepare ](https://github.com/facebookresearch/SlowFast/blob/master/slowfast/datasets/DATASET.md)ava 2.1 dataset.

Created config file based on [SLOWFAST_32x2_R101_50_50_v2.1.yaml](https://github.com/facebookresearch/SlowFast/blob/46484164fc585951aec646ef323d5982542b5bb3/configs/AVA/c2/SLOWFAST_32x2_R101_50_50_v2.1.yaml), here **(https://pastebin.pl/view/01c5251a).**

**Expected behavior**
Model Trains successfully

Ran model using command:
`python tools/run_net.py --cfg configs/AVA/SLOWFAST_32x2_R101_50_50_custom.yaml DATA.PATH_TO_DATA_DIR "G:\video-long-term-feature-banks-master\data\ava" NUM_GPUS 1 TRAIN.BATCH_SIZE 32`

Edit: Also tried with ava 2.2 with the same issue

After 2 epochs i get the msg: [full log](https://pastebin.pl/view/73ba4e83)
```
[09/28 21:34:31][INFO] slowfast.datasets.ava_dataset:   88: === AVA dataset summary ===
[09/28 21:34:31][INFO] slowfast.datasets.ava_dataset:   89: Split: train
[09/28 21:34:31][INFO] slowfast.datasets.ava_dataset:   90: Number of videos: 235
[09/28 21:34:31][INFO] slowfast.datasets.ava_dataset:   94: Number of frames: 6352104
[09/28 21:34:31][INFO] slowfast.datasets.ava_dataset:   95: Number of key frames: 184378
[09/28 21:34:31][INFO] slowfast.datasets.ava_dataset:   96: Number of boxes: 332353.
[09/28 21:34:31][INFO] train_net:  416: Start epoch: 2
Traceback (most recent call last):
  File "tools/run_net.py", line 43, in <module>
    main()
  File "tools/run_net.py", line 24, in main
    launch_job(cfg=cfg, init_method=args.init_method, func=train)
  File "c:\users\theza\documents\cvtd\slowfast\slowfast\utils\misc.py", line 288, in launch_job
    func(cfg=cfg)
  File "C:\Users\theza\Documents\CVTD\slowfast\tools\train_net.py", line 447, in train
    train_loader, model, optimizer, train_meter, cur_epoch, cfg, writer
  File "C:\Users\theza\Documents\CVTD\slowfast\tools\train_net.py", line 48, in train_epoch
    for cur_iter, (inputs, labels, _, meta) in enumerate(train_loader):
  File "C:\Users\theza\Anaconda3\envs\CVTD2\lib\site-packages\torch\utils\data\dataloader.py", line 363, in __next__
    data = self._next_data()
  File "C:\Users\theza\Anaconda3\envs\CVTD2\lib\site-packages\torch\utils\data\dataloader.py", line 989, in _next_data
    return self._process_data(data)
  File "C:\Users\theza\Anaconda3\envs\CVTD2\lib\site-packages\torch\utils\data\dataloader.py", line 1014, in _process_data
    data.reraise()
  File "C:\Users\theza\Anaconda3\envs\CVTD2\lib\site-packages\torch\_utils.py", line 395, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "C:\Users\theza\Anaconda3\envs\CVTD2\lib\site-packages\torch\utils\data\_utils\worker.py", line 185, in _worker_loop
    data = fetcher.fetch(index)
  File "C:\Users\theza\Anaconda3\envs\CVTD2\lib\site-packages\torch\utils\data\_utils\fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "C:\Users\theza\Anaconda3\envs\CVTD2\lib\site-packages\torch\utils\data\_utils\collate.py", line 84, in default_collate
    return [default_collate(samples) for samples in transposed]
  File "C:\Users\theza\Anaconda3\envs\CVTD2\lib\site-packages\torch\utils\data\_utils\collate.py", line 84, in <listcomp>
    return [default_collate(samples) for samples in transposed]
  File "C:\Users\theza\Anaconda3\envs\CVTD2\lib\site-packages\torch\utils\data\_utils\collate.py", line 64, in default_collate
    return default_collate([torch.as_tensor(b) for b in batch])
  File "C:\Users\theza\Anaconda3\envs\CVTD2\lib\site-packages\torch\utils\data\_utils\collate.py", line 55, in default_collate
    return torch.stack(batch, 0, out=out)
RuntimeError: stack expects each tensor to be equal size, but got [10, 80] at entry 0 and [1, 80] at entry 1
```

**Environment**

- Windows 10 
- 64 GB ram
- RTX 1660 S 6GB

I can do inference using the pretrained models.

**Comment by thezaza101** [comment]
Closing issue. This seems to be due to having DETECTION disabled/not enough VRAM. Was able to get this training on AWS ml.p3.8xlarge with a batch size of 16
