### ISSUE TITLE
model load

### ISSUE THREAD

**Issue by Lysemo** [facebookresearch/SlowFast#299]
when use torch.load to load pretrain-model, arise error belowed:
Traceback (most recent call last):
  File "C:/Users/Lysemo/Desktop/linux/SlowFast/model/test.py", line 3, in <module>
    checkpoint = torch.load('SLOWFAST_32x2_R101_50_50_v2.1.pkl',map_location='cuda:0')
  File "D:\ProgramFiles\Anaconda3\envs\Torch1.6\lib\site-packages\torch\serialization.py", line 585, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "D:\ProgramFiles\Anaconda3\envs\Torch1.6\lib\site-packages\torch\serialization.py", line 755, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa4 in position 5: invalid start byte
please help me, Thanks.

**Comment by anandankm** [comment]
I got a similar error. Can someone help?

```
---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
<ipython-input-23-0c59d85fa04e> in <module>
----> 1 cu.load_test_checkpoint(cfg, model)

~/Downloads/Other/SlowFast/SlowFast/slowfast/utils/checkpoint.py in load_test_checkpoint(cfg, model)
    405             None,
    406             inflation=False,
--> 407             convert_from_caffe2=cfg.TEST.CHECKPOINT_TYPE == "caffe2",
    408         )
    409     elif has_checkpoint(cfg.OUTPUT_DIR):

~/Downloads/Other/SlowFast/SlowFast/slowfast/utils/checkpoint.py in load_checkpoint(path_to_checkpoint, model, data_parallel, optimizer, inflation, convert_from_caffe2)
    263         # Load the checkpoint on CPU to avoid GPU mem spike.
    264         with PathManager.open(path_to_checkpoint, "rb") as f:
--> 265             checkpoint = torch.load(f, map_location="cpu")
    266         model_state_dict_3d = (
    267             model.module.state_dict() if data_parallel else model.state_dict()

~/opt/miniconda3/envs/pytorch_p37/lib/python3.7/site-packages/torch/serialization.py in load(f, map_location, pickle_module, **pickle_load_args)
    583                     return torch.jit.load(opened_file)
    584                 return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
--> 585         return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
    586 
    587 

~/opt/miniconda3/envs/pytorch_p37/lib/python3.7/site-packages/torch/serialization.py in _legacy_load(f, map_location, pickle_module, **pickle_load_args)
    753             "functionality.".format(type(f)))
    754 
--> 755     magic_number = pickle_module.load(f, **pickle_load_args)
    756     if magic_number != MAGIC_NUMBER:
    757         raise RuntimeError("Invalid magic number; corrupt file?")

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd4 in position 1: invalid continuation byte
```

**Comment by anandankm** [comment]
Never mind. This worked: `cfg.TEST.CHECKPOINT_TYPE = "caffe2"`

**Comment by 17Skye17** [comment]
Same problem here

**Comment by kinjmshah** [comment]
@anandankm where did you place that line in order to avoid the issue? Thank you in advance for your help!

**Comment by Ricardoluffy** [comment]
> Never mind. This worked: `cfg.TEST.CHECKPOINT_TYPE = "caffe2"`

it's helpful ！thanks
