### ISSUE TITLE
When i trian the model,I got this issue.

### ISSUE THREAD

**Issue by zhaoleo1111** [facebookresearch/SlowFast#305]
Traceback (most recent call last):
  File "tools/run_net.py", line 42, in <module>
    main()
  File "tools/run_net.py", line 23, in main
    launch_job(cfg=cfg, init_method=args.init_method, func=train)
  File "/home/leo/my_project/SlowFast/slowfast/utils/misc.py", line 296, in launch_job
    func(cfg=cfg)
  File "/home/leo/my_project/SlowFast/tools/train_net.py", line 393, in train
    train_loader = loader.construct_loader(cfg, "train")
  File "/home/leo/my_project/SlowFast/slowfast/datasets/loader.py", line 83, in construct_loader
    dataset = build_dataset(dataset_name, cfg, split)
  File "/home/leo/my_project/SlowFast/slowfast/datasets/build.py", line 31, in build_dataset
    return DATASET_REGISTRY.get(name)(cfg, split)
  File "/home/leo/my_project/SlowFast/slowfast/datasets/kinetics.py", line 74, in __init__
    self._construct_loader()
  File "/home/leo/my_project/SlowFast/slowfast/datasets/kinetics.py", line 94, in _construct_loader
    == 2
AssertionErro

**Comment by PhelimonSarpaning** [comment]
have you found a solution?

**Comment by jaylnne** [comment]
I had the same error, and i solved it by decreasing **NUM_WORKER** 8 to 5. 
I don't know if this is the exact solution, but the subprocess that runs too much while loading the data may have caused the problem.

**Comment by nash100** [comment]
i have the same problem. i find the reason:
my train.csv, val.csv format is
path_to_video_1, label_1
path_to_video_2 ,label_2
not the same with [https://github.com/facebookresearch/SlowFast/blob/master/slowfast/datasets/DATASET.md](url)
i just add 
PATH_LABEL_SEPARATOR: ","
to yaml in "DATA"

**Comment by Bhavik-Ardeshna** [comment]
@nash100 

```
Traceback (most recent call last):
  File "tools/run_net.py", line 52, in <module>
    main()
  File "tools/run_net.py", line 27, in main
    launch_job(cfg=cfg, init_method=args.init_method, func=train)
  File "/content/slowfast/slowfast/utils/misc.py", line 430, in launch_job
    func(cfg=cfg)
  File "/content/slowfast/tools/train_net.py", line 681, in train
    train_epoch(
  File "/content/slowfast/tools/train_net.py", line 276, in train_epoch
    del inputs
UnboundLocalError: local variable 'inputs' referenced before assignment
```

Getting this error. Will you please help me out with it.
