### ISSUE TITLE
Error whilst trying to run ava demo

### ISSUE THREAD

**Issue by PhelimonSarpaning** [facebookresearch/SlowFast#349]
Traceback (most recent call last):
  File "tools/run_net.py", line 51, in <module>
    main()
  File "tools/run_net.py", line 47, in main
    demo(cfg)
  File "/home/SlowFast-master/tools/demo_net.py", line 114, in demo
    for task in tqdm.tqdm(run_demo(cfg, frame_provider)):
  File "/home/venv/lib/python3.6/site-packages/tqdm/std.py", line 1167, in __iter__
    for obj in iterable:
  File "/home/SlowFast-master/tools/demo_net.py", line 59, in run_demo
    model = ActionPredictor(cfg=cfg, async_vis=async_vis)
  File "/home/SlowFast-master/slowfast/visualization/predictor.py", line 132, in __init__
    self.predictor = Predictor(cfg=cfg, gpu_id=gpu_id)
  File "/home/SlowFast-master/slowfast/visualization/predictor.py", line 46, in __init__
    cu.load_test_checkpoint(cfg, self.model)
  File "/home/SlowFast-master/slowfast/utils/checkpoint.py", line 468, in load_test_checkpoint
    load_checkpoint(last_checkpoint, model, cfg.NUM_GPUS > 1)
  File "/home/SlowFast-master/slowfast/utils/checkpoint.py", line 285, in load_checkpoint
    checkpoint = torch.load(f, map_location="cpu")
  File "/home/venv/lib/python3.6/site-packages/torch/serialization.py", line 587, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/home/venv/lib/python3.6/site-packages/torch/serialization.py", line 242, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: [enforce fail at inline_container.cc:145] . PytorchStreamReader failed reading zip archive: failed finding central directory

**Comment by LevShechter** [comment]
Hi, I am just dealing with the same problem, 
did u solve it?
can I ask what parameters did u put?
Thanks!!
Lev

**Comment by siwarammar** [comment]
Hi @PhelimonSarpaning, 
I am also encountering the same issue.
let me know how you solved it if you did so.
