### ISSUE TITLE
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_INITIALIZED

### ISSUE THREAD

**Issue by wzj9812** [facebookresearch/SlowFast#384]
Trying to re-implement this code on Cloud Server, however I can't get past this cuda error. Any help on this?
Traceback (most recent call last):
  File "tools/run_net.py", line 45, in <module>
    main()
  File "tools/run_net.py", line 41, in main
    demo(cfg)
  File "/home/slowfast/tools/demo_net.py", line 114, in demo
    for task in tqdm.tqdm(run_demo(cfg, frame_provider)):
  File "/opt/conda/lib/python3.7/site-packages/tqdm/std.py", line 1167, in __iter__
    for obj in iterable:
  File "/home/slowfast/tools/demo_net.py", line 79, in run_demo
    model.put(task)
  File "/home/slowfast/slowfast/visualization/predictor.py", line 142, in put
    task = self.predictor(task)
  File "/home/slowfast/slowfast/visualization/predictor.py", line 61, in __call__
    task = self.object_detector(task)
  File "/home/slowfast/slowfast/visualization/predictor.py", line 201, in __call__
    outputs = self.predictor(middle_frame)
  File "/opt/conda/lib/python3.7/site-packages/detectron2/engine/defaults.py", line 251, in __call__
    predictions = self.model([inputs])[0]
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/detectron2/modeling/meta_arch/rcnn.py", line 149, in forward
    return self.inference(batched_inputs)
  File "/opt/conda/lib/python3.7/site-packages/detectron2/modeling/meta_arch/rcnn.py", line 203, in inference
    features = self.backbone(images.tensor)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/detectron2/modeling/backbone/fpn.py", line 126, in forward
    bottom_up_features = self.bottom_up(x)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/detectron2/modeling/backbone/resnet.py", line 444, in forward
    x = self.stem(x)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/detectron2/modeling/backbone/resnet.py", line 355, in forward
    x = self.conv1(x)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/detectron2/layers/wrappers.py", line 85, in forward
    x, self.weight, self.bias, self.stride, self.padding, self.dilation, self.groups
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_INITIALIZED

**Comment by balaganeshmohan** [comment]
If by cloud you mean colab? Then just restart the environment and it would work. Or you can check your cuda sstatus with !nvidia-smi
