### ISSUE TITLE
ImportError: libopenh264.so.5:

### ISSUE THREAD

**Issue by hansdom** [facebookresearch/SlowFast#396]
root@60797751e8758e862573b6dc:~# cd /home/slowfast/
root@60797751e8758e862573b6dc:/home/slowfast# python tools/run_net.py --cfg demo/AVA/SLOWFAST_32x2_R101_50_50.yaml
Traceback (most recent call last):
  File "tools/run_net.py", line 5, in <module>
    from slowfast.utils.misc import launch_job
  File "/home/slowfast/slowfast/utils/misc.py", line 20, in <module>
    from slowfast.datasets.utils import pack_pathway_output
  File "/home/slowfast/slowfast/datasets/__init__.py", line 7, in <module>
    from .kinetics import Kinetics  # noqa
  File "/home/slowfast/slowfast/datasets/kinetics.py", line 14, in <module>
    from . import video_container as container
  File "/home/slowfast/slowfast/datasets/video_container.py", line 4, in <module>
    import av
  File "/opt/conda/lib/python3.7/site-packages/av/__init__.py", line 9, in <module>
    from av._core import time_base, pyav_version as __version__, library_versions
ImportError: libopenh264.so.5: cannot open shared object file: No such file or directory

**Comment by MarkusFox** [comment]
I faced the same issue with FFmpeg 4.3 in a Python 3.8 environment.

I solved it similar to the answer of william007 [HERE](https://stackoverflow.com/questions/62213783/ffmpeg-error-while-loading-shared-libraries-libopenh264-so-5).

In my environment called 'pyslowfast' I was able to locate `~/anaconda3/envs/pyslowfast/lib/libopenh264.so.6`. I made a copy of the file and renamed it, e.g. `cp ~/anaconda3/envs/pyslowfast/lib/libopenh264.so.6 ~/anaconda3/envs/pyslowfast/lib/libopenh264.so.5`. After that the error was gone and I was able to train a model using this repository.

Not sure if this is the best answer but it works so far.
