### ISSUE TITLE
RuntimeError: CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by burgosmad** [facebookresearch/SlowFast#418]
[05/12 11:09:35][INFO] train_net.py: 417: Start epoch: 1
[05/12 11:09:44][INFO] logging.py:  99: json_stats: {"_type": "train_iter", "dt": 0.75089, "dt_data": 0.00221, "dt_net": 0.74868, "epoch": "1/196", "eta": "4 days, 1:27:37", "gpu_mem": "2.59G", "iter": "10/2384", "loss": 5.14431, "lr": 0.01001, "top1_err": 100.00000, "top5_err": 100.00000}
[05/12 11:09:51][INFO] logging.py:  99: json_stats: {"_type": "train_iter", "dt": 0.76528, "dt_data": 0.00199, "dt_net": 0.76328, "epoch": "1/196", "eta": "4 days, 3:19:30", "gpu_mem": "2.59G", "iter": "20/2384", "loss": 5.73635, "lr": 0.01002, "top1_err": 100.00000, "top5_err": 100.00000}
[05/12 11:09:59][INFO] logging.py:  99: json_stats: {"_type": "train_iter", "dt": 0.76246, "dt_data": 0.00184, "dt_net": 0.76062, "epoch": "1/196", "eta": "4 days, 2:57:28", "gpu_mem": "2.59G", "iter": "30/2384", "loss": 5.88172, "lr": 0.01003, "top1_err": 100.00000, "top5_err": 100.00000}
[05/12 11:10:06][INFO] logging.py:  99: json_stats: {"_type": "train_iter", "dt": 0.75784, "dt_data": 0.00186, "dt_net": 0.75598, "epoch": "1/196", "eta": "4 days, 2:21:20", "gpu_mem": "2.59G", "iter": "40/2384", "loss": 5.55687, "lr": 0.01004, "top1_err": 100.00000, "top5_err": 100.00000}
[05/12 11:10:14][INFO] logging.py:  99: json_stats: {"_type": "train_iter", "dt": 0.75887, "dt_data": 0.00186, "dt_net": 0.75701, "epoch": "1/196", "eta": "4 days, 2:29:16", "gpu_mem": "2.59G", "iter": "50/2384", "loss": 6.14274, "lr": 0.01005, "top1_err": 100.00000, "top5_err": 100.00000}
[05/12 11:10:21][INFO] logging.py:  99: json_stats: {"_type": "train_iter", "dt": 0.75892, "dt_data": 0.00239, "dt_net": 0.75652, "epoch": "1/196", "eta": "4 days, 2:29:28", "gpu_mem": "2.59G", "iter": "60/2384", "loss": 5.48882, "lr": 0.01006, "top1_err": 100.00000, "top5_err": 100.00000}
[05/12 11:10:29][INFO] logging.py:  99: json_stats: {"_type": "train_iter", "dt": 0.75781, "dt_data": 0.00188, "dt_net": 0.75593, "epoch": "1/196", "eta": "4 days, 2:20:44", "gpu_mem": "2.59G", "iter": "70/2384", "loss": 5.96438, "lr": 0.01007, "top1_err": 100.00000, "top5_err": 100.00000}
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:108: cunn_ClassNLLCriterion_updateOutput_kernel: block: [0,0,0], thread: [1,0,0] Assertion `t >= 0 && t < n_classes` failed.
Traceback (most recent call last):
  File "tools/run_net.py", line 44, in <module>
    main()
  File "tools/run_net.py", line 25, in main
    launch_job(cfg=cfg, init_method=args.init_method, func=train)
  File "/001/usuarios/burgosmad/slowfast/slowfast/utils/misc.py", line 297, in launch_job
    func(cfg=cfg)
  File "/001/usuarios/burgosmad/slowfast/tools/train_net.py", line 451, in train
    train_loader, model, optimizer, train_meter, cur_epoch, cfg, writer
  File "/001/usuarios/burgosmad/slowfast/tools/train_net.py", line 82, in train_epoch
    misc.check_nan_losses(loss)
  File "/001/usuarios/burgosmad/slowfast/slowfast/utils/misc.py", line 32, in check_nan_losses
    if math.isnan(loss):
RuntimeError: CUDA error: device-side assert triggered_

I am trying to implement SlowFast with UCF101 because I don't have the technology to use Kinetics yet. I guess this error is related to:
1.- UCF-101 is divided into 3 splits of train and 3 splits of test and here we are using a *.csv for train, test and val. I already tried some configurations but I am getting this error. How can I create this 3 sets?
2.- Maybe, UCF101 is too small and I would need to fine tune from Kinetics. I would like to know where can I find the Kinetics pre-trained model for fine-tuning with UCF101 and also if you can share the script (I found that the code was shared but only in a personalized way)

Any idea? 
Thanks in advance.

**Comment by Abiems** [comment]
Hi @burgosmad  can you please tell me how did you solve this problem ?

**Comment by burgosmad** [comment]
Of course, the first thing I did was cry and then I discovered that my classes were from 0 to 100 and not from 1 to 101. The clue was "Assertion t >= 0 && t < n_classes failed."
 I hope it works for you.
Regards
