### ISSUE TITLE
AssertionError: Invalid type <class 'NoneType'> for key POOL_KVQ_KERNEL;

### ISSUE THREAD

**Issue by vba34520** [facebookresearch/SlowFast#437]
Execute
```shell
python tools/run_net.py --cfg demo/AVA/SLOWFAST_32x2_R101_50_50.yaml
```
It cause
```
Traceback (most recent call last):
  File "tools/run_net.py", line 5, in <module>
    from slowfast.config.defaults import assert_and_infer_cfg
  File "/home/xercis/code/slowfast/slowfast/config/defaults.py", line 357, in <module>
    _C.MVIT.POOL_KVQ_KERNEL = None
  File "/home/xercis/anaconda3/envs/py38/lib/python3.8/site-packages/fvcore/common/config.py", line 148, in __setattr__
    super().__setattr__(name, val)
  File "/home/xercis/anaconda3/envs/py38/lib/python3.8/site-packages/yacs/config.py", line 155, in __setattr__
    _assert_with_logging(
  File "/home/xercis/anaconda3/envs/py38/lib/python3.8/site-packages/yacs/config.py", line 521, in _assert_with_logging
    assert cond, msg
AssertionError: Invalid type <class 'NoneType'> for key POOL_KVQ_KERNEL; valid types = {<class 'list'>, <class 'bool'>, <class 'tuple'>, <class 'int'>, <class 'str'>, <class 'float'>}
```
My environment
```
CUDA 10.1
cuDNN 7.6.3
detectron2=0.4.1
fvcore==0.1.5.post20210624
slowfast==1.0
torch==1.7.1
torchaudio==0.7.0a0+a853dff
torchvision==0.8.2
yacs==0.1.6
```
SLOWFAST_32x2_R101_50_50.yaml
```yaml
TRAIN:
  ENABLE: False
  DATASET: ava
  BATCH_SIZE: 16
  EVAL_PERIOD: 1
  CHECKPOINT_PERIOD: 1
  AUTO_RESUME: True
  CHECKPOINT_FILE_PATH: "/home/xercis/code/slowfast/demo/AVA/SLOWFAST_32x2_R101_50_50.pkl"  #path to pretrain model
  CHECKPOINT_TYPE: pytorch
DATA:
  NUM_FRAMES: 32
  SAMPLING_RATE: 2
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 256
  INPUT_CHANNEL_NUM: [3, 3]
DETECTION:
  ENABLE: True
  ALIGNED: False
AVA:
  BGR: False
  DETECTION_SCORE_THRESH: 0.8
  TEST_PREDICT_BOX_LISTS: ["person_box_67091280_iou90/ava_detection_val_boxes_and_labels.csv"]
SLOWFAST:
  ALPHA: 4
  BETA_INV: 8
  FUSION_CONV_CHANNEL_RATIO: 2
  FUSION_KERNEL_SZ: 5
RESNET:
  ZERO_INIT_FINAL_BN: True
  WIDTH_PER_GROUP: 64
  NUM_GROUPS: 1
  DEPTH: 101
  TRANS_FUNC: bottleneck_transform
  STRIDE_1X1: False
  NUM_BLOCK_TEMP_KERNEL: [[3, 3], [4, 4], [6, 6], [3, 3]]
  SPATIAL_DILATIONS: [[1, 1], [1, 1], [1, 1], [2, 2]]
  SPATIAL_STRIDES: [[1, 1], [2, 2], [2, 2], [1, 1]]
NONLOCAL:
  LOCATION: [[[], []], [[], []], [[6, 13, 20], []], [[], []]]
  GROUP: [[1, 1], [1, 1], [1, 1], [1, 1]]
  INSTANTIATION: dot_product
  POOL: [[[2, 2, 2], [2, 2, 2]], [[2, 2, 2], [2, 2, 2]], [[2, 2, 2], [2, 2, 2]], [[2, 2, 2], [2, 2, 2]]]
BN:
  USE_PRECISE_STATS: False
  NUM_BATCHES_PRECISE: 200
SOLVER:
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-7
  OPTIMIZING_METHOD: sgd
MODEL:
  NUM_CLASSES: 80
  ARCH: slowfast
  MODEL_NAME: SlowFast
  LOSS_FUNC: bce
  DROPOUT_RATE: 0.5
  HEAD_ACT: sigmoid
TEST:
  ENABLE: False
  DATASET: ava
  BATCH_SIZE: 8
DATA_LOADER:
  NUM_WORKERS: 2
  PIN_MEMORY: True

NUM_GPUS: 1
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: .
#TENSORBOARD:
#  MODEL_VIS:
#    TOPK: 2
DEMO:
  ENABLE: True
  LABEL_FILE_PATH: "/home/xercis/code/slowfast/demo/AVA/ava.json"
#  WEBCAM: 0
  INPUT_VIDEO: "/home/xercis/code/slowfast/demo/AVA/1.mp4"
  OUTPUT_FILE: "/home/xercis/code/slowfast/demo/AVA/2.mp4"
  DETECTRON2_CFG: "COCO-Detection/faster_rcnn_R_50_FPN_3x.yaml"
  DETECTRON2_WEIGHTS: detectron2://COCO-Detection/faster_rcnn_R_50_FPN_3x/137849458/model_final_280758.pkl
```

Looking forward to your help!

**Comment by vba34520** [comment]
Solved by execute
```shell
pip install yacs==0.1.8
```
