### ISSUE TITLE
I can't run models from MODEL ZOO

### ISSUE THREAD

**Issue by darkAlert** [facebookresearch/SlowFast#439]
I am trying to run a checkpoint from MODEL ZOO like this:
```
python3 tools/run_net.py --cfg configs/Kinetics/c2/SLOWFAST_8x8_R50.yaml \
DATA.PATH_TO_DATA_DIR /Kinetics700/k700_test_001/Kinetics700-2020-test \
TEST.CHECKPOINT_FILE_PATH /checkpoints/SLOWFAST_8x8_R50.pkl \
TRAIN.ENABLE False NUM_GPUS 2
```

 but I get the following error every time:
```
-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/home/darkalert/.local/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/home/darkalert/OtusJob/computer_vision/Action Recognition/slowfast/slowfast/utils/multiprocessing.py", line 60, in run
    ret = func(cfg)
  File "/home/darkalert/OtusJob/computer_vision/Action Recognition/slowfast/tools/test_net.py", line 165, in test
    cu.load_test_checkpoint(cfg, model)
  File "/home/darkalert/OtusJob/computer_vision/Action Recognition/slowfast/slowfast/utils/checkpoint.py", line 458, in load_test_checkpoint
    load_checkpoint(
  File "/home/darkalert/OtusJob/computer_vision/Action Recognition/slowfast/slowfast/utils/checkpoint.py", line 285, in load_checkpoint
    checkpoint = torch.load(f, map_location="cpu")
  File "/home/darkalert/.local/lib/python3.8/site-packages/torch/serialization.py", line 593, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/darkalert/.local/lib/python3.8/site-packages/torch/serialization.py", line 762, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd4 in position 1: invalid continuation byte
```

My PyTorch version is  '1.8.1+cu102'

**Comment by darkAlert** [comment]
Ok, it's my fault. I missed the argument: `TEST.CHECKPOINT_TYPE caffe2`
