### ISSUE TITLE
Training on Custom Dataset

### ISSUE THREAD

**Issue by lizha0yan** [facebookresearch/SlowFast#440]
Hi Team,
I successfully built the model, and prepare the dataset to follow the structure in [issue149](https://github.com/facebookresearch/SlowFast/issues/149). Then when I tried to run
 `python tools/run_net.py --cfg configs/mydata/I3D_8*8_R50.yaml`
It returns SyntaxError:

```
root@827654e8bdc8:/ActionRecognition/slowfast# python tools/run_net.py --cfg configs/mydata/I3D_8*8_R50.yaml
Traceback (most recent call last):
  File "tools/run_net.py", line 5, in <module>
    from slowfast.utils.misc import launch_job
  File "/ActionRecognition/slowfast/slowfast/__init__.py", line 4, in <module>
    from slowfast.utils.env import setup_environment
  File "/ActionRecognition/slowfast/slowfast/utils/env.py", line 6, in <module>
    import slowfast.utils.logging as logging
  File "/ActionRecognition/slowfast/slowfast/utils/logging.py", line 24
    def print_pass(*objects, sep=" ", end="\n", file=sys.stdout, flush=False):
                               ^
SyntaxError: invalid syntax
```
Can you give me some advice on where is the problem and how to fix it? Thanks a lot!

**Comment by haooooooqi** [comment]
Hey @lizha0yan,

Thanks for playing with PySF! Could you remind me if you use python3?

Thanks,
Haoqi

**Comment by lizha0yan** [comment]
Hi Haoqi，
Thanks for getting back to me. Yes, I'm using python3.

Regards,

Zhaoyan Li
Phone: 5103309424
Email: ***@***.***
Linkedin: https://www.linkedin.com/in/zhaoyan-li/

**Comment by lizha0yan** [comment]
> Hey @lizha0yan,
> 
> Thanks for playing with PySF! Could you remind me if you use python3?
> 
> Thanks,
> Haoqi

Hi Haoqi,
After I changed to python3 it worked. Thanks for the help! 
Now I'm facing another problem.
`root@407074a699ac:/ActionRecognition/slowfast# python3 tools/run_net.py --cfg configs/mydata/I3D_8*8_R50.yaml
Traceback (most recent call last):
  File "tools/run_net.py", line 5, in <module>
    from slowfast.utils.misc import launch_job
  File "/ActionRecognition/slowfast/slowfast/utils/misc.py", line 20, in <module>
    from slowfast.datasets.utils import pack_pathway_output
  File "/ActionRecognition/slowfast/slowfast/datasets/__init__.py", line 10, in <module>
    from .mydata import mydata
  File "/ActionRecognition/slowfast/slowfast/datasets/mydata.py", line 21, in <module>
    class Kinetics(torch.utils.data.Dataset):
  File "/usr/local/lib/python3.8/dist-packages/fvcore/common/registry.py", line 59, in deco
    self._do_register(name, func_or_class)
  File "/usr/local/lib/python3.8/dist-packages/fvcore/common/registry.py", line 43, in _do_register
    assert (
AssertionError: An object named 'Kinetics' was already registered in 'DATASET' registry!`
I already change the 'Kinetics' into 'mydata' according to the [issue149](https://github.com/facebookresearch/SlowFast/issues/149).
I really appreciate your help!
