### ISSUE TITLE
from torchvision.transforms.functional import InterpolationMode ImportError: cannot import name 'InterpolationMode'

### ISSUE THREAD

**Issue by NEUdeep** [facebookresearch/SlowFast#441]
from torchvision.transforms.functional import InterpolationMode
ImportError: cannot import name 'InterpolationMode'

it is not InterpolationMode in PyTorch, how to solve it?

**Comment by haooooooqi** [comment]
Hey @NEUdeep 
Thanks for playing with PySF. Sorry I don't quite follow, could you remind me where do we use `InterpolationMode`? Maybe update your pytorch/ torchvision might help. If updating does not work, could you share me the full stack?

Thanks,
Haoqi

**Comment by Aloha0424** [comment]
> Hey @NEUdeep
> Thanks for playing with PySF. Sorry I don't quite follow, could you remind me where do we use `InterpolationMode`? Maybe update your pytorch/ torchvision might help. If updating does not work, could you share me the full stack?
> 
> Thanks,
> Haoqi

Hi,I met the same problem. The full error stack is as follows:
Traceback (most recent call last):
  File "slowfast/tools/run_net.py", line 6, in <module>
    from slowfast.utils.misc import launch_job
  File "/mnt/dl-storage/test-cephfs-0/group/asr/CCKS_video/slowfast/slowfast/utils/misc.py", line 20, in <module>
    from slowfast.datasets.utils import pack_pathway_output
  File "/mnt/dl-storage/test-cephfs-0/group/asr/CCKS_video/slowfast/slowfast/datasets/__init__.py", line 9, in <module>
    from .ptv_datasets import Ptvcharades, Ptvkinetics, Ptvssv2  # noqa
  File "/mnt/dl-storage/test-cephfs-0/group/asr/CCKS_video/slowfast/slowfast/datasets/ptv_datasets.py", line 28, in <module>
    from pytorchvideo.transforms import (
  File "/mnt/dl-storage/test-cephfs-0/group/asr/envs/anaconda3/envs/pytorch/lib/python3.8/site-packages/pytorchvideo/transforms/__init__.py", line 3, in <module>
    from .augmix import AugMix  # noqa
  File "/mnt/dl-storage/test-cephfs-0/group/asr/envs/anaconda3/envs/pytorch/lib/python3.8/site-packages/pytorchvideo/transforms/augmix.py", line 6, in <module>
    from pytorchvideo.transforms.augmentations import AugmentTransform
  File "/mnt/dl-storage/test-cephfs-0/group/asr/envs/anaconda3/envs/pytorch/lib/python3.8/site-packages/pytorchvideo/transforms/augmentations.py", line 10, in <module>
    from torchvision.transforms.functional import InterpolationMode
ImportError: cannot import name 'InterpolationMode' from 'torchvision.transforms.functional' (/mnt/dl-storage/test-cephfs-0/group/asr/envs/anaconda3/envs/pytorch/lib/python3.8/site-packages/torchvision/transforms/functional.py)

**Comment by haooooooqi** [comment]
![image](https://user-images.githubusercontent.com/3500423/124074634-a51a1980-d9f8-11eb-9966-d11099e3eada.png)

**Comment by haooooooqi** [comment]
Hi All,

I see, this might be a version mismatch issue between PySF and PyTorchVideo. Could you pull on PyTorchVideo and try it again?
cc @lyttonhao 

Thanks,
Haoqi

**Comment by haooooooqi** [comment]
Aloha @Aloha0424 @NEUdeep,
A temporal fix is landing 
:)

**Comment by gqsmile** [comment]
hello，I encountered the same problem, did you solve it?

**Comment by talhaanwarch** [comment]
This functionality is added in latter version, if you are using an older version of torchvision for example 0.8.2 you can get this error. If you dont want to upgrade, simly copy the code and put in your code
