### ISSUE TITLE
ValueError: numpy.ndarray size changed, may indicate binary incompatibility.

### ISSUE THREAD

**Issue by cliff0917** [facebookresearch/SlowFast#453]
Traceback (most recent call last):
  File "tools/run_net.py", line 14, in <module>
    from test_net import test
  File "/home/uscc/Desktop/cliff/electronic_pet/tools/test_net.py", line 14, in <module>
    from slowfast.models import model_builder
  File "/home/uscc/Desktop/cliff/electronic_pet/slowfast/models/model_builder.py", line 8, in <module>
    from slowfast.models.video_model_builder import ResNetModel, SlowFastModel
  File "/home/uscc/Desktop/cliff/electronic_pet/slowfast/models/video_model_builder.py", line 10, in <module>
    from slowfast.models import head_helper, resnet_helper, stem_helper
  File "/home/uscc/Desktop/cliff/electronic_pet/slowfast/models/head_helper.py", line 8, in <module>
    from detectron2.layers import ROIAlign
  File "/home/uscc/Desktop/SlowFast-master/detectron2_repo/detectron2/layers/__init__.py", line 4, in <module>
    from .mask_ops import paste_masks_in_image
  File "/home/uscc/Desktop/SlowFast-master/detectron2_repo/detectron2/layers/mask_ops.py", line 8, in <module>
    from detectron2.structures import Boxes
  File "/home/uscc/Desktop/SlowFast-master/detectron2_repo/detectron2/structures/__init__.py", line 7, in <module>
    from .masks import BitMasks, PolygonMasks, polygons_to_bitmask, ROIMasks
  File "/home/uscc/Desktop/SlowFast-master/detectron2_repo/detectron2/structures/masks.py", line 6, in <module>
    import pycocotools.mask as mask_util
  File "/home/uscc/anaconda3/envs/py37/lib/python3.7/site-packages/pycocotools/mask.py", line 3, in <module>
    import pycocotools._mask as _mask
  File "pycocotools/_mask.pyx", line 1, in init pycocotools._mask
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
 
Does anyone know how to fix it? I can run slowfast before... 
my python version is 3.7, and numpy version is 1.19.5

**Comment by coolbay** [comment]
@cliff0917 Did you solve the issue?

**Comment by cliff0917** [comment]
> @cliff0917 Did you solve the issue?

Yes, just update your numpy

**Comment by coolbay** [comment]
@cliff0917 Thanks very much! It works for me as well.
