### ISSUE TITLE
Multi GPU Single Machine Training not working

### ISSUE THREAD

**Issue by a-maiti** [facebookresearch/SlowFast#470]
Hi, 
Thanks for open sourcing this wonderful codebase. I am trying to train the pretrained K400 model on charades on a single machine multi-GPU setting but I am unable to do so. I am getting the following error when I make `NUM_GPUS: 2` in the config. 
```
(action-dg) ubuntu@nipa2021-16090:~/users/maiti/projects/action-recognition-da/baseline$ python -m torch.distributed.launch  slowfast_baseline_multigpu.py
Please update your PyTorchVideo to latest master
Traceback (most recent call last):
  File "slowfast_baseline_multigpu.py", line 39, in <module>
    train_net.train(cfg)
  File "/home/ubuntu/users/maiti/projects/SlowFast/pysftools/train_net.py", line 390, in train
    du.init_distributed_training(cfg)
  File "/home/ubuntu/users/maiti/projects/SlowFast/slowfast/utils/distributed.py", line 275, in init_distributed_training
    num_machines = dist.get_world_size() // num_gpus_per_machine
  File "/home/ubuntu/anaconda3/envs/action-dg/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 638, in get_world_size
    return _get_group_size(group)
  File "/home/ubuntu/anaconda3/envs/action-dg/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 220, in _get_group_size
    _check_default_pg()
  File "/home/ubuntu/anaconda3/envs/action-dg/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 210, in _check_default_pg
    assert _default_pg is not None, \
AssertionError: Default process group is not initialized
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/action-dg/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/ubuntu/anaconda3/envs/action-dg/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/anaconda3/envs/action-dg/lib/python3.8/site-packages/torch/distributed/launch.py", line 260, in <module>
    main()
  File "/home/ubuntu/anaconda3/envs/action-dg/lib/python3.8/site-packages/torch/distributed/launch.py", line 255, in main
    raise subprocess.CalledProcessError(returncode=process.returncode,
subprocess.CalledProcessError: Command '['/home/ubuntu/anaconda3/envs/action-dg/bin/python', '-u', 'slowfast_baseline_multigpu.py', '--local_rank=0']' returned non-zero exit status 1.
```
The command I ran is `python -m torch.distributed.launch  slowfast_baseline_multigpu.py`. The single GPU version is running fine. 
I also added the following lines before the main code executes 
```
torch.distributed.init_process_group(backend="nccl")
```
but no luck. Or if anyone could provide a script for running single machine multi GPU training, with the changes that I need to make.  
I really appreciate any inputs. 
Thanks

**Comment by a-maiti** [comment]
Sorry, my bad. This is fixed.

**Comment by umarkhalidAI** [comment]
> @a-maiti can you tell me how to fix it, I got a similar problem. :(

Any feedback what causes this problem?
