### ISSUE TITLE
KeyError: '"-5KQ66BBWC4'," -5KQ66BBWC4"is  the one of name of video

### ISSUE THREAD

**Issue by ChouCHou-y** [facebookresearch/SlowFast#479]
when i train the model,it will  pesents this issue.
[09/17 06:46:34][INFO] ava_helper.py: 110: Number of unique boxes: 2204
[09/17 06:46:34][INFO] ava_helper.py: 111: Number of annotations: 7089
Traceback (most recent call last):
  File "tools/run_net.py", line 44, in <module>
    main()
  File "tools/run_net.py", line 25, in main
    launch_job(cfg=cfg, init_method=args.init_method, func=train)
  File "/home/yanzhouquan/code/slowfast/SlowFast/slowfast/utils/misc.py", line 311, in launch_job
    func(cfg=cfg)
  File "/home/yanzhouquan/code/slowfast/SlowFast/tools/train_net.py", line 429, in train
    train_loader = loader.construct_loader(cfg, "train")
  File "/home/yanzhouquan/code/slowfast/SlowFast/slowfast/datasets/loader.py", line 109, in construct_loader
    dataset = build_dataset(dataset_name, cfg, split)
  File "/home/yanzhouquan/code/slowfast/SlowFast/slowfast/datasets/build.py", line 31, in build_dataset
    return DATASET_REGISTRY.get(name)(cfg, split)
  File "/home/yanzhouquan/code/slowfast/SlowFast/slowfast/datasets/ava_dataset.py", line 47, in __init__
    self._load_data(cfg)
  File "/home/yanzhouquan/code/slowfast/SlowFast/slowfast/datasets/ava_dataset.py", line 69, in _load_data
    boxes_and_labels = [
  File "/home/yanzhouquan/code/slowfast/SlowFast/slowfast/datasets/ava_dataset.py", line 70, in <listcomp>
    boxes_and_labels[self._video_idx_to_name[i]]
KeyError: '"-5KQ66BBWC4'

**Comment by ValentinKovalev** [comment]
Hello. There could name an error in the filename because it contains the symbol `"`. Try to replace/delete it.

**Comment by ChouCHou-y** [comment]
> Hello. There could name an error in the filename because it contains the symbol `"`. Try to replace/delete it.

sorry！it contains the symbol `"` like this file,but i don't think the error is here ,it will lead to more errror after delete it . I cant't find the error where  from  is ,so sad.

![U5_U_3S7K2RIO}G$)35H~N2](https://user-images.githubusercontent.com/81743349/134610026-0cea0a2b-5742-4c73-8bc3-2fe6e64eef92.png)
![W0KRWCSR DF) DU05I$BN7](https://user-images.githubusercontent.com/81743349/134610027-aec7d9fb-32fb-413e-84e2-676e36588c93.png)

**Comment by okiane** [comment]
> > Hello. There could name an error in the filename because it contains the symbol `"`. Try to replace/delete it.
> 
> sorry！it contains the symbol `"` like this file,but i don't think the error is here ,it will lead to more errror after delete it . I cant't find the error where from is ,so sad.
> 
> ![U5_U_3S7K2RIO}G$)35H~N2](https://user-images.githubusercontent.com/81743349/134610026-0cea0a2b-5742-4c73-8bc3-2fe6e64eef92.png)
> ![W0KRWCSR DF) DU05I$BN7](https://user-images.githubusercontent.com/81743349/134610027-aec7d9fb-32fb-413e-84e2-676e36588c93.png)

Try renaming those folders and files that starts with -. as it is frequently used as option tags for linux commands (e.g. ls -al). 
Replacing it with another character should work. Remember to change your annotation file accordingly.

**Comment by xxxxy888** [comment]
I have the same problem, my filename is '1',may I ask how you resolved it?
error:
boxes_and_labels[self._video_idx_to_name[i]]
KeyError: '1'

@ChouCHou-y

**Comment by Lxzzzzzzzzzzz** [comment]
i have the same problem,how to solve it?

**Comment by Zhang-zhaoxin** [comment]
Do not use office software to process any CSV format files. Use text editors instead. If you are on a Windows system, open the files with Notepad. If you are on an Ubuntu system, use vim to open the files. Because Excel or the office software that comes with Ubuntu can cause the CSV file to become garbled.

**Comment by pepper725** [comment]
> i have the same problem,how to solve it?

have you solved  this problem,please

**Comment by Zhang-zhaoxin** [comment]
> > i have the same problem,how to solve it?
> 
> have you solved this problem,please

Do not use office software to process any CSV format files. Use text editors instead. If you are on a Windows system, open the files with Notepad. If you are on an Ubuntu system, use vim to open the files. Because Excel or the office software that comes with Ubuntu can cause the CSV file to become garbled.

**Comment by ArthurKirkland241** [comment]
> 不要使用办公软件处理任何 CSV 格式的文件。使用文本编辑器代替。如果您使用的是 Windows 系统，请使用记事本打开文件。如果您使用的是 Ubuntu 系统，请使用 Vim 打开文件。因为 Excel 或 Ubuntu 附带的办公软件可能会导致 CSV 文件变得乱码。

You saved my life. You are the cutest person I have ever met this year.
