### ISSUE TITLE
Unable to download kinetic dataset. 400, 600, 700. Following problems are arises. how can i solve it ?

### ISSUE THREAD

**Issue by ldeepk** [facebookresearch/SlowFast#485]
python download.py kinetics_700_2020_train.csv kinetics_700_2020_train
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/kamakhya/anaconda3/envs/ldeepk_test_slowfast_1/lib/python3.9/site-packages/joblib/externals/loky/process_executor.py", line 431, in _process_worker
    r = call_item()
  File "/home/kamakhya/anaconda3/envs/ldeepk_test_slowfast_1/lib/python3.9/site-packages/joblib/externals/loky/process_executor.py", line 285, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/home/kamakhya/anaconda3/envs/ldeepk_test_slowfast_1/lib/python3.9/site-packages/joblib/_parallel_backends.py", line 595, in __call__
    return self.func(*args, **kwargs)
  File "/home/kamakhya/anaconda3/envs/ldeepk_test_slowfast_1/lib/python3.9/site-packages/joblib/parallel.py", line 262, in __call__
    return [func(*args, **kwargs)
  File "/home/kamakhya/anaconda3/envs/ldeepk_test_slowfast_1/lib/python3.9/site-packages/joblib/parallel.py", line 262, in <listcomp>
    return [func(*args, **kwargs)
  File "/media/kamakhya/460935cd-01e9-438f-959d-6595ff14f1bb/Lakhyadeep/Kinetics_700_dataset_2020_all/download.py", line 130, in download_clip_wrapper
    downloaded, log = download_clip(row['video-id'], output_filename,
  File "/media/kamakhya/460935cd-01e9-438f-959d-6595ff14f1bb/Lakhyadeep/Kinetics_700_dataset_2020_all/download.py", line 117, in download_clip
    os.remove(tmp_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/kinetics/13d9d2a8-fa27-447a-bec4-1e74ffd5af72.mp4'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/media/kamakhya/460935cd-01e9-438f-959d-6595ff14f1bb/Lakhyadeep/Kinetics_700_dataset_2020_all/download.py", line 220, in <module>
    main(**vars(p.parse_args()))
  File "/media/kamakhya/460935cd-01e9-438f-959d-6595ff14f1bb/Lakhyadeep/Kinetics_700_dataset_2020_all/download.py", line 191, in main
    status_lst = Parallel(n_jobs=num_jobs)(delayed(download_clip_wrapper)(
  File "/home/kamakhya/anaconda3/envs/ldeepk_test_slowfast_1/lib/python3.9/site-packages/joblib/parallel.py", line 1054, in __call__
    self.retrieve()
  File "/home/kamakhya/anaconda3/envs/ldeepk_test_slowfast_1/lib/python3.9/site-packages/joblib/parallel.py", line 933, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/kamakhya/anaconda3/envs/ldeepk_test_slowfast_1/lib/python3.9/site-packages/joblib/_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "/home/kamakhya/anaconda3/envs/ldeepk_test_slowfast_1/lib/python3.9/concurrent/futures/_base.py", line 438, in result
    return self.__get_result()
  File "/home/kamakhya/anaconda3/envs/ldeepk_test_slowfast_1/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/kinetics/13d9d2a8-fa27-447a-bec4-1e74ffd5af72.mp4'

**Comment by Andy1621** [comment]
You can follow [here](https://github.com/cvdfoundation/kinetics-dataset) to download kinetics.

Welcome to try our [UniFormer](https://github.com/Sense-X/UniFormer), we provide details to reproduce SOTA results for SSV2.

**Comment by ldeepk** [comment]
Thank you.
