### ISSUE TITLE
Not able load pretrained models from model zoo

### ISSUE THREAD

**Issue by vikramguptai** [facebookresearch/SlowFast#499]
Thanks for sharing this great repo. I want to finetune pretrained I3D/SlowFast models on my custom dataset. 

However, I am not able to load the pretrained models downloaded from the model zoo:
https://github.com/facebookresearch/SlowFast/blob/main/MODEL_ZOO.md

The X3D pretrained models get successfully loaded so does not seem like a code issue. Please help. Looks like some python version mismatch issue. 

```
import torch
torch.load("I3D_NLN_8x8_R50.pkl")
torch.load("I3D_8x8_R50.pkl")
torch.load("SLOWFAST_8x8_R50.pkl")
```
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/envs/mmaction/lib/python3.7/site-packages/torch/serialization.py", line 593, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/opt/conda/envs/mmaction/lib/python3.7/site-packages/torch/serialization.py", line 762, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbc in position 14: invalid start byte
```

Thank You !

**Comment by vikramguptai** [comment]
Fixed this by setting TRAIN.CHECKPOINT_TYPE="caffe2" for these models.

Closing the issue now. Thanks.
