### ISSUE TITLE
OSError: [Errno 12] Cannot allocate memory (My graphics card is 3080,)

### ISSUE THREAD

**Issue by KIdFlash233** [facebookresearch/SlowFast#510]
Hi, I downloaded the Charades dataset and tried to train the dataset with the command:
> python tools/run_net.py --cfg configs/Charades/SLOWFAST_16x8_R50.yaml

BATCH_SIZE: 1
DATA_LOADER:
  NUM_WORKERS: 1 
  PIN_MEMORY: True
NUM_GPUS: 1        
NUM_SHARDS: 1
RNG_SEED: 0

I got the following error,
[01/17 16:45:05][INFO] charades.py:  71: Constructing Charades train...
[01/17 16:46:10][INFO] charades.py: 109: Charades dataloader constructed (size: 7811) from /home/SlowFast-main/data/charades/frame_lists/train.csv
[01/17 16:46:10][INFO] charades.py:  71: Constructing Charades val...
[01/17 16:46:25][INFO] charades.py: 109: Charades dataloader constructed (size: 1814) from /home/SlowFast-main/data/charades/frame_lists/val.csv
[01/17 16:46:25][INFO] charades.py:  71: Constructing Charades train...
[01/17 16:47:29][INFO] charades.py: 109: Charades dataloader constructed (size: 7811) from /home/SlowFast-main/data/charades/frame_lists/train.csv
[01/17 16:47:29][INFO] train_net.py: 468: Start epoch: 1
Traceback (most recent call last):
  File "tools/run_net.py", line 44, in <module>
    main()
  File "tools/run_net.py", line 25, in main
    launch_job(cfg=cfg, init_method=args.init_method, func=train)
  File "/home/SlowFast-main/slowfast/utils/misc.py", line 311, in launch_job
    func(cfg=cfg)
  File "/home/slowFast-main/tools/train_net.py", line 509, in train
    writer,
  File "/home/SlowFast-main/tools/train_net.py", line 67, in train_epoch
    for cur_iter, (inputs, labels, _, meta) in enumerate(train_loader):
  File "/home/anaconda3/envs/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 355, in __iter__
    return self._get_iterator()
  File "/home/xuwenqiang/anaconda3/envs/flash/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 301, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/home/anaconda3/envs/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 914, in __init__
    w.start()
  File "/home/python3.7/multiprocessing/process.py", line 112, in start
    self._popen = self._Popen(self)
  File "/home/anaconda3/envs/lib/python3.7/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/home/anaconda3/envs/lib/python3.7/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/home/anaconda3/envs/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/home/anaconda3/envs/lib/python3.7/multiprocessing/popen_fork.py", line 70, in _launch
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory

I wonder if you could point out what is going wrong.

Many Thanks!

And,please tell me that what is the minimum video memory,RAM,and configuration required for slowfast code?
My graphics card is 3080,is the configuration not enough?

Many Thanks!

**Comment by BonGum** [comment]
Do you find the solution？I meet same trouble as yours
