### ISSUE TITLE
KeyError: 1

### ISSUE THREAD

**Issue by mxy-699699** [facebookresearch/SlowFast#536]
hello，when i use “python tools/run_net.py --cfg configs/AVA/SLOWFAST_32x2_R50_SHORT.yaml” to train，the following error occurs

The following error occurs
Traceback (most recent call last):
  File "tools/run_net.py", line 46, in <module>
    main()
  File "tools/run_net.py", line 27, in main
    launch_job(cfg=cfg, init_method=args.init_method, func=train)
  File "/home/vision/mxy1/SlowFast/slowfast/utils/misc.py", line 311, in launch_job
    func(cfg=cfg)
  File "/exdata/mxy/SlowFast/tools/train_net.py", line 443, in train
    train_loader = loader.construct_loader(cfg, "train")
  File "/home/vision/mxy1/SlowFast/slowfast/datasets/loader.py", line 109, in construct_loader
    dataset = build_dataset(dataset_name, cfg, split)
  File "/home/vision/mxy1/SlowFast/slowfast/datasets/build.py", line 31, in build_dataset
    return DATASET_REGISTRY.get(name)(cfg, split)
  File "/home/vision/mxy1/SlowFast/slowfast/datasets/ava_dataset.py", line 47, in __init__
    self._load_data(cfg)
  File "/home/vision/mxy1/SlowFast/slowfast/datasets/ava_dataset.py", line 63, in _load_data
    boxes_and_labels = ava_helper.load_boxes_and_labels(
  File "/home/vision/mxy1/SlowFast/slowfast/datasets/ava_helper.py", line 101, in load_boxes_and_labels
    all_boxes, count, unique_box_count = parse_bboxes_file(
  File "/home/vision/mxy1/SlowFast/slowfast/datasets/ava_helper.py", line 222, in parse_bboxes_file
    if box_key not in all_boxes[video_name][frame_sec]:
KeyError: 1

I've tried many ways, but I can't solve it. Can you help me，thank you very much

**Comment by mxy-699699** [comment]
刚刚把问题解决啦

**Comment by lixunst** [comment]
您好，我也遇到了这个问题，
请问如何解决的呢

**Comment by lixunst** [comment]
> 刚刚把问题解决啦

您好，我也遇到了这个问题，
请问如何解决的呢

**Comment by fusu80** [comment]
我现在来请教一下还不算晚吧?

**Comment by xobeiotozi** [comment]
@mxy-699699 How did you solve the problem？

**Comment by JHhuiP** [comment]
> 刚刚把问题解决啦

求助大佬，请问您是如何解决的呢
