### ISSUE TITLE
UnboundLocalError: local variable 'inputs' referenced before assignment

### ISSUE THREAD

**Issue by balakishan777** [facebookresearch/SlowFast#547]
The below error is encountered during finetuning. It is happening because of line 89 **enumerate(train_loader)** in tools/train_net.py is empty. But I am not sure why this is empty.
                      Traceback (most recent call last):
                        File "tools/run_net.py", line 45, in <module>
                          main()
                        File "tools/run_net.py", line 26, in main
                          launch_job(cfg=cfg, init_method=args.init_method, func=train)
                        File "/activty_recognizer/slowfast/slowfast/utils/misc.py", line 311, in launch_job
                          func(cfg=cfg)
                        File "/activty_recognizer/ava_training/SlowFast/tools/train_net.py", line 714, in train
                          train_epoch(
                        File "/activty_recognizer/ava_training/SlowFast/tools/train_net.py", line 265, in train_epoch
                          del inputs
                      UnboundLocalError: local variable 'inputs' referenced before assignment

But train_loader has this data:
                {'dataset': <slowfast.datasets.ava_dataset.Ava object at 0x7faf74ee4610>, 'num_workers': 2, 'prefetch_factor': 2, 'pin_memory': True, 'timeout': 0, 'worker_init_fn': None, '_DataLoader__multiprocessing_context': None, '_dataset_kind': 0, 'batch_size': 8, 'drop_last': True, 'sampler': <torch.utils.data.sampler.RandomSampler object at 0x7faf74ee45b0>, 'batch_sampler':<torch.utils.data.sampler.BatchSampler object at 0x7faf74ee46d0>, 'generator': None, 'collate_fn': <function detection_collate at 0x7faf7438b940>, 'persistent_workers': False, '_DataLoader__initialized': True, '_IterableDataset_len_called': None, '_iterator': None}_

**Comment by ahmedwael19** [comment]
same error here

**Comment by haooooooqi** [comment]
Hmmmm could you remind me why inputs are not assigned?
(a fix is del the del input)

**Comment by imzhangyd** [comment]
same error, have you fixed it?

**Comment by Bhavik-Ardeshna** [comment]
@haooooooqi 
@imzhangyd 
@balakishan777 
```
Traceback (most recent call last):
  File "tools/run_net.py", line 52, in <module>
    main()
  File "tools/run_net.py", line 27, in main
    launch_job(cfg=cfg, init_method=args.init_method, func=train)
  File "/content/slowfast/slowfast/utils/misc.py", line 430, in launch_job
    func(cfg=cfg)
  File "/content/slowfast/tools/train_net.py", line 681, in train
    train_epoch(
  File "/content/slowfast/tools/train_net.py", line 276, in train_epoch
    del inputs
UnboundLocalError: local variable 'inputs' referenced before assignment
```
I am also getting the same issue will you please help me out?

**Comment by XuesenYang** [comment]
I know why, because the number of training videos is smaller than batch_size, changing TRAIN.BATCH_SIZE to be smaller than the number of training videos in the yaml file or config/defaults.py can solve the problem.

**Comment by devvaibhav455** [comment]
@XuesenYang : Thanks, your suggestion worked!
