### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9e in position 0: invalid start byte

### ISSUE THREAD

**Issue by balakishan777** [facebookresearch/SlowFast#548]
### I am facing this issue when I am trying to load a pre trained model in pytorch format. I am trying custom training using AVA dataset and using the below config.
***
TRAIN:
  ENABLE: True
  DATASET: ava
  BATCH_SIZE: 8
  EVAL_PERIOD: 5
  CHECKPOINT_PERIOD: 1
  AUTO_RESUME: True
  CHECKPOINT_FILE_PATH: /slowfast/configs/AVA/c2/SLOWFAST_32x2_R101_50_50.pkl'
  CHECKPOINT_TYPE: pytorch
***
Below code is causing the issue.
        with pathmgr.open(path_to_checkpoint, "rb") as f:
            checkpoint = torch.load(f, map_location="cpu")
***

####  Could any one suggest how to fix this?
***
_Traceback (most recent call last):
  File "tools/run_net.py", line 45, in <module>
    main()
  File "tools/run_net.py", line 26, in main
    launch_job(cfg=cfg, init_method=args.init_method, func=train)
  File "/slowfast/slowfast/utils/misc.py", line 311, in launch_job
    func(cfg=cfg)
  File "/slowfast/tools/train_net.py", line 611, in train
    checkpoint_epoch = cu.load_checkpoint(
  File /slowfast/slowfast/utils/checkpoint.py", line 301, in load_checkpoint
    checkpoint = torch.load(f, map_location="cpu")
  File "/anaconda/envs/env_actvity8/lib/python3.8/site-packages/torch/serialization.py", line 713, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/anaconda/envs/env_actvity8/lib/python3.8/site-packages/torch/serialization.py", line 920, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9e in position 0: invalid start byte_

**Comment by Splending6** [comment]
it seems the CHECKPOINT_TYPE of the official model is caffe2

**Comment by balakishan777** [comment]
I have tried with "CHECKPOINT_TYPE as caffe2", getting the below error. Unable to load and getting errors with any of the CHECKPOINT_TYPE.<br> 
It is happening because of  **_enumerate(train_loader)_**  in line 89 in tools/train_net.py is empty. But I am not sure why this is empty.
***
**But train_loader has this data before passing it to the function:**<br>
{'dataset': <slowfast.datasets.ava_dataset.Ava object at 0x7faf74ee4610>, 'num_workers': 2, 'prefetch_factor': 2, 'pin_memory': True, 'timeout': 0, 'worker_init_fn': None, '_DataLoader__multiprocessing_context': None, '_dataset_kind': 0, 'batch_size': 8, 'drop_last': True, 'sampler': <torch.utils.data.sampler.RandomSampler object at 0x7faf74ee45b0>, 'batch_sampler':<torch.utils.data.sampler.BatchSampler object at 0x7faf74ee46d0>, 'generator': None, 'collate_fn': <function detection_collate at 0x7faf7438b940>, 'persistent_workers': False, '_DataLoader__initialized': True, '_IterableDataset_len_called': None, 'iterator': None}
***
Traceback (most recent call last):
  File "tools/run_net.py", line 45, in <module>
    main()
  File "tools/run_net.py", line 26, in main
    launch_job(cfg=cfg, init_method=args.init_method, func=train)
  File "/slowfast/slowfast/utils/misc.py", line 311, in launch_job
    func(cfg=cfg)
  File "/slowfast/tools/train_net.py", line 715, in train
    train_epoch(
  File "/slowfast/tools/train_net.py", line 265, in train_epoch
    del inputs
UnboundLocalError: local variable 'inputs' referenced before assignment
***

**Comment by ZiyingHuang** [comment]
Hello, I met the same error with you. Have you solved it?
