### ISSUE TITLE
I think there are some errors in file 'test_net.py'.

### ISSUE THREAD

**Issue by Splending6** [facebookresearch/SlowFast#549]
I think there are some errors in file 'test_net.py'.
First I run the official code, but it says:

`-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/home/dinghan/anaconda3/envs/slowfast/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/home/dinghan/SlowFast/slowfast/utils/multiprocessing.py", line 60, in run
    ret = func(cfg)
  File "/home/dinghan/SlowFast/tools/test_net.py", line 243, in test
    test_meter = perform_test(test_loader, model, test_meter, cfg, writer)
  File "/home/dinghan/anaconda3/envs/slowfast/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/dinghan/SlowFast/tools/test_net.py", line 124, in perform_test
    preds, labels, video_idx = du.all_gather(
  File "/home/dinghan/SlowFast/slowfast/utils/distributed.py", line 39, in all_gather
    dist.all_gather(tensor_placeholder, tensor, async_op=False)
  File "/home/dinghan/anaconda3/envs/slowfast/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 1863, in all_gather
    work = default_pg.allgather([tensor_list], [tensor])
RuntimeError: Tensors must be CUDA and dense
`
I think in file 'test_net.py', line 124-133 is duplicate with line 77-90. Or maybe the indentation?

**Comment by chuntiz** [comment]
Same problem here. Did you solve it?

**Comment by dfan** [comment]
I think lines 123-135 can be moved under the condition `if not cfg.DETECTION.ENABLE`, which fixes the above issue, but getting very low mAP.

**Comment by haooooooqi** [comment]
Thanks for playing with PySlowFast

@lyttonhao have you seen this problem before when running AVA?

**Comment by zhangAxin** [comment]
使用官方下载的模型去跑，出现(pytorch) D:\SlowFast\SlowFast-main>python tools/run_net.py --cfg demo/AVA/SLOWFAST_32x2_R101_50_50.yaml
Traceback (most recent call last):
  File "D:\SlowFast\SlowFast-main\tools\run_net.py", line 5, in <module>
    from slowfast.config.defaults import assert_and_infer_cfg
ImportError: cannot import name 'assert_and_infer_cfg' from 'slowfast.config.defaults' (D:\ProgramData\anaconda3\envs\pytorch\lib\site-packages\slowfast\config\defaults.py)
错误信息，一直解决不了，请问有没有大神可以指点一下

**Comment by Run542968** [comment]
> I think lines 123-135 can be moved under the condition `if not cfg.DETECTION.ENABLE`, which fixes the above issue, but getting very low mAP.

Hi, I meet the same problem the mAP is very low after disabling the code in lines 124-133. Do you solve this problem?

**Comment by Run542968** [comment]
> I think lines 123-135 can be moved under the condition `if not cfg.DETECTION.ENABLE`, which fixes the above issue, but getting very low mAP.

@dfan Hi, I meet the same problem the mAP is very low after disabling the code in lines 124-133. Do you solve this problem?

**Comment by Run542968** [comment]
I find the code in lines 124-133 should be typed, it may be a sub-code after "else".😶

**Comment by 3210448723** [comment]
我发现如果我只使用一个GPU测试则不会出现这个问题。
I found that I wouldn't encounter this problem if I only used one GPU test.

**Comment by huwenfeng233** [comment]
> 使用官方下载的模型去跑，出现(pytorch) D:\SlowFast\SlowFast-main>python tools/run_net.py --cfg demo/AVA/SLOWFAST_32x2_R101_50_50.yaml Traceback (most recent call last): File "D:\SlowFast\SlowFast-main\tools\run_net.py", line 5, in from slowfast.config.defaults import assert_and_infer_cfg ImportError: cannot import name 'assert_and_infer_cfg' from 'slowfast.config.defaults' (D:\ProgramData\anaconda3\envs\pytorch\lib\site-packages\slowfast\config\defaults.py) 错误信息，一直解决不了，请问有没有大神可以指点一下

`export PYTHONPATH=/path/to/SlowFast/slowfast:$PYTHONPATH`
执行下这句话
