### ISSUE TITLE
use pyav read the video data, throw "local variable 'start_end_delta_time' referenced before assignment". A BUG

### ISSUE THREAD

**Issue by StawEndl** [facebookresearch/SlowFast#557]
i report some bug,maybe.

`Traceback (most recent call last):
  File "tools/run_net.py", line 60, in <module>
    main()
  File "tools/run_net.py", line 41, in main
    launch_job(cfg=cfg, init_method=args.init_method, func=train)
  File "/home/mopanzhong/rope_detection/SlowFast-main/slowfast/utils/misc.py", line 312, in launch_job
    func(cfg=cfg)
  File "/home/mopanzhong/rope_detection/SlowFast-main/tools/train_net.py", line 708, in train
    train_epoch(
  File "/home/mopanzhong/rope_detection/SlowFast-main/tools/train_net.py", line 86, in train_epoch
    for cur_iter, (inputs, labels, index, time, meta) in enumerate(train_loader):
  File "/home/mopanzhong/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/mopanzhong/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/home/mopanzhong/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/home/mopanzhong/.local/lib/python3.8/site-packages/torch/_utils.py", line 434, in reraise
    raise exception
UnboundLocalError: Caught UnboundLocalError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/mopanzhong/.local/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/mopanzhong/.local/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/mopanzhong/.local/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/mopanzhong/rope_detection/SlowFast-main/slowfast/datasets/kinetics.py", line 344, in __getitem__
    frames, time_idx, tdiff = decoder.decode(
  File "/home/mopanzhong/rope_detection/SlowFast-main/slowfast/datasets/decoder.py", line 627, in decode
    return frames_out, start_end_delta_time, time_diff_aug
UnboundLocalError: local variable 'start_end_delta_time' referenced before assignment
`

i use the pyav_decode functiopn to read the video, but **this function return  the decode_all_video which is False. When decode_all_video is False, the start_end_delta_time is not created.**

if you fix this bug, please tell me.

**Comment by haooooooqi** [comment]
Thanks for playing with PySF!
Seems you have modified the code, I don't see start_end_delta_time at line 627
