### ISSUE TITLE
AssertionError: test.csv dir not found

### ISSUE THREAD

**Issue by AliButtarRB** [facebookresearch/SlowFast#585]
Hi,

I am just trying to use SlowFast to perform inference on my own videos using the pre-trained models. I have updated the config to include the `DEMO` key and its relevant details. I am using this `'configs/Kinetics/c2/C2D_NOPOOL_8x8_R50.yaml'` config.

I run this command to perform inference: `!python tools/run_net.py --cfg config.yaml`
But I keep getting the above error. 

You can view [this notebook](https://colab.research.google.com/drive/1Vl0OMrA5tL0EnlnkC6Z0xjxxGLx5QklB?usp=sharing) to see the whole picture

**Comment by alpargun** [comment]
Can you also include your dataset structure? Normally, your kinetics dataset directory should have the train.csv, val.csv and test.csv files that include the paths to all the videos for each partition with their label.

**Comment by davidfreire** [comment]
Just add:
config['TEST'] = {
    'ENABLE': False
}

**Comment by pepper725** [comment]
how did you solve the problem

**Comment by pepper725** [comment]
> Just add:
> 
> config['TEST'] = {
> 
>     'ENABLE': False
> 
> }

If I adopt this method, new errors will be reported. like train.csv not  found

**Comment by davidfreire** [comment]
> > Just add:
> > config['TEST'] = {
> > ```
> > 'ENABLE': False
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > }
> 
> If I adopt this method, new errors will be reported. like train.csv not found

It depends on what you're trying to achieve. Are you focusing on training, or are you conducting tests?

**Comment by pepper725** [comment]
> > > Just add:
> > > config['TEST'] = {
> > > ```
> > > 'ENABLE': False
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > }
> > 
> > 
> > If I adopt this method, new errors will be reported. like train.csv not found
> 
> It depends on what you're trying to achieve. Are you focusing on training, or are you conducting tests?

The task I'm trying to train for, the command I'm typing in looks like this.
python tools/run_net.py \
  --cfg configs/Kinetics/C2D_8x8_R50.yaml \
  DATA.PATH_TO_DATA_DIR/mnt/data1/DATASETs/kinetics400/kinetics400/ \
  NUM_GPUS 2 \
  TRAIN.BATCH_SIZE 16 \
 And the error reported is something like the following:
 Traceback (most recent call last):
  File "/home/user/.conda/envs/hja_py10/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/mnt/data1/hja/SlowFast/slowfast/utils/multiprocessing.py", line 60, in run
    ret = func(cfg)
  File "/mnt/data1/hja/SlowFast/tools/train_net.py", line 590, in train
    train_loader = loader.construct_loader(cfg, "train")
  File "/mnt/data1/hja/SlowFast/slowfast/datasets/loader.py", line 115, in construct_loader
    dataset = build_dataset(dataset_name, cfg, split)
  File "/mnt/data1/hja/SlowFast/slowfast/datasets/build.py", line 31, in build_dataset
    return DATASET_REGISTRY.get(name)(cfg, split)
  File "/mnt/data1/hja/SlowFast/slowfast/datasets/kinetics.py", line 91, in __init__
    self._construct_loader()
  File "/mnt/data1/hja/SlowFast/slowfast/datasets/kinetics.py", line 110, in _construct_loader
    assert pathmgr.exists(path_to_file), "{} dir not found".format(path_to_file)
AssertionError: train.csv dir not found

**Comment by davidfreire** [comment]
> AssertionError: train.csv dir not found

This error typically occurs when the training data file `train.csv` is either missing or not located in the directory specified in the configuration file. Check the config file.

Best

**Comment by pepper725** [comment]
> > AssertionError: train.csv dir not found
> 
> This error typically occurs when the training data file `train.csv` is either missing or not located in the directory specified in the configuration file. Check the config file.
> 
> Best
Hi, what is the format of the train.csv file 'spaghetti,--3ouPhoy2A,20,30,train' something like this correct?
