### ISSUE TITLE
a bug about test_net.py

### ISSUE THREAD

**Issue by ping-High** [facebookresearch/SlowFast#599]
After I updated the code version, this bug appeared in the test.I compared the code of the previous version and found that the problem really appeared in the updated code. I hope the official can fix it as soon as possible.
```
Traceback (most recent call last):
  File "tools/run_net.py", line 52, in <module>
    main()
  File "tools/run_net.py", line 37, in main
    launch_job(cfg=cfg, init_method=args.init_method, func=test)
  File "/opt/data/private/SlowFast/slowfast/utils/misc.py", line 430, in launch_job
    func(cfg=cfg)
  File "/opt/data/private/SlowFast/tools/test_net.py", line 252, in test
    test_meter = perform_test(test_loader, model, test_meter, cfg, writer)
  File "/root/miniconda3/envs/slowfast/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/opt/data/private/SlowFast/tools/test_net.py", line 129, in perform_test
    test_meter.iter_toc()
  File "/opt/data/private/SlowFast/slowfast/utils/meters.py", line 159, in iter_toc
    self.iter_timer.pause()
  File "/root/miniconda3/envs/slowfast/lib/python3.8/site-packages/fvcore/common/timer.py", line 30, in pause
    raise ValueError("Trying to pause a Timer that is already paused!")
ValueError: Trying to pause a Timer that is already paused!
```

**Comment by KonoDioooda** [comment]
Same problem. Have you found the resolution

**Comment by Nnnorth-South** [comment]
#623 和这个回答一样，找到早期的test_net代码进行替换

**Comment by Whiffe** [comment]
![image](https://github.com/facebookresearch/SlowFast/assets/33534050/889215f5-4e24-4fd1-9fe0-e06a94cff286)
I modified the code of test_net.py. The modified content is shown in the figure

`        # Gather all the predictions across all the devices to perform ensemble.
        if cfg.NUM_GPUS > 1:
            preds, labels, video_idx = du.all_gather([preds, labels, video_idx])
        if cfg.NUM_GPUS:
            preds = preds.cpu()
            labels = labels.cpu()
            video_idx = video_idx.cpu()

        try:
            test_meter.iter_toc()
        except:
            pass
        if not cfg.VIS_MASK.ENABLE:
            # Update and log stats.
            test_meter.update_stats(
                preds.detach(), labels.detach(), video_idx.detach()
            )
        try:
            test_meter.log_iter_stats(cur_iter)
        except:
            test_meter.log_iter_stats(None,cur_iter)

        test_meter.iter_tic()`

**Comment by Whiffe** [comment]
![image](https://github.com/facebookresearch/SlowFast/assets/33534050/889215f5-4e24-4fd1-9fe0-e06a94cff286)
I modified the code of test_net.py. The modified content is shown in the figure

About 120 to 140 lines

        if cfg.NUM_GPUS > 1:
            preds, labels, video_idx = du.all_gather([preds, labels, video_idx])
        if cfg.NUM_GPUS:
            preds = preds.cpu()
            labels = labels.cpu()
            video_idx = video_idx.cpu()

        try:
            test_meter.iter_toc()
        except:
            pass
        if not cfg.VIS_MASK.ENABLE:
            # Update and log stats.
            test_meter.update_stats(
                preds.detach(), labels.detach(), video_idx.detach()
            )
        try:
            test_meter.log_iter_stats(cur_iter)
        except:
            test_meter.log_iter_stats(None,cur_iter)

        test_meter.iter_tic()
