### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory:'data/ava/frames/NEQ7Wpf-EtI/NEQ7Wpf-EtI_023159.jpg'

### ISSUE THREAD

**Issue by khandriod** [facebookresearch/SlowFast#611]
Hi, as the title suggest, I am getting this error. I am using AVA dataset. 
The reason is that I cut the video to 5 minutes instead of 15 minutes and some frames are missing. How to fix this? I can not find the code where it looks for frames.

```
[10/06 23:36:16][INFO] ava_dataset.py:   88: === AVA dataset summary ===
[10/06 23:36:16][INFO] ava_dataset.py:   89: Split: val
[10/06 23:36:16][INFO] ava_dataset.py:   90: Number of videos: 64
[10/06 23:36:16][INFO] ava_dataset.py:   94: Number of frames: 1729931
[10/06 23:36:16][INFO] ava_dataset.py:   95: Number of key frames: 13169
[10/06 23:36:16][INFO] ava_dataset.py:   96: Number of boxes: 24863.
[10/06 23:36:24][INFO] ava_helper.py:   62: Finished loading image paths from: ./data/ava/frame_list/train.csv
[10/06 23:36:28][INFO] ava_helper.py:   62: Finished loading image paths from: ./data/ava/frame_list/val.csv
[10/06 23:36:28][INFO] train_net.py:  631: Start epoch: 1
Traceback (most recent call last):
  File "/home/yeji/Jabbar/models/slowfast/tools/run_net.py", line 52, in <module>
    main()
  File "/home/yeji/Jabbar/models/slowfast/tools/run_net.py", line 27, in main
    launch_job(cfg=cfg, init_method=args.init_method, func=train)
  File "/home/yeji/Jabbar/models/slowfast/slowfast/utils/misc.py", line 430, in launch_job
    func(cfg=cfg)
  File "/home/yeji/Jabbar/models/slowfast/tools/train_net.py", line 681, in train
    train_epoch(
  File "/home/yeji/Jabbar/models/slowfast/tools/train_net.py", line 77, in train_epoch
    for cur_iter, (inputs, labels, index, time, meta) in enumerate(
  File "/home/yeji/anaconda3/envs/sf1/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 652, in __next__
    data = self._next_data()
  File "/home/yeji/anaconda3/envs/sf1/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1347, in _next_data
    return self._process_data(data)
  File "/home/yeji/anaconda3/envs/sf1/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1373, in _process_data
    data.reraise()
  File "/home/yeji/anaconda3/envs/sf1/lib/python3.9/site-packages/torch/_utils.py", line 461, in reraise
    raise exception
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/yeji/anaconda3/envs/sf1/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/yeji/anaconda3/envs/sf1/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/yeji/anaconda3/envs/sf1/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/yeji/Jabbar/models/slowfast/slowfast/datasets/ava_dataset.py", line 399, in __getitem__
    imgs = utils.retry_load_images(
  File "/home/yeji/Jabbar/models/slowfast/slowfast/datasets/utils.py", line 41, in retry_load_images
    with pathmgr.open(image_path, "rb") as f:
  File "/home/yeji/anaconda3/envs/sf1/lib/python3.9/site-packages/iopath/common/file_io.py", line 1012, in open
    bret = handler._open(path, mode, buffering=buffering, **kwargs)  # type: ignore
  File "/home/yeji/anaconda3/envs/sf1/lib/python3.9/site-packages/iopath/common/file_io.py", line 604, in _open
    return open(  # type: ignore
FileNotFoundError: [Errno 2] No such file or directory: 'data/ava/frames/NEQ7Wpf-EtI/NEQ7Wpf-EtI_023159.jpg'

````

**Comment by khandriod** [comment]
I found that **ava_helper.py**  needs to be formated for that.
```
   list_filenames = [
        os.path.join(cfg.AVA.FRAME_LIST_DIR, filename)
        for filename in (
            cfg.AVA.TRAIN_LISTS if is_train else cfg.AVA.TEST_LISTS
        )
    ]
    image_paths = defaultdict(list)
    video_name_to_idx = {}
    video_idx_to_name = []
    for list_filename in list_filenames:
        with pathmgr.open(list_filename, "r") as f:
            f.readline()
            for line in f:
                row = line.split()
                # The format of each row should follow:
                # original_vido_id video_id frame_id path labels.
                assert len(row) == 5
                video_name = row[0]
                frame_image = row[-2] #Jabbar Edited

                import pdb; pdb.set_trace()                

                #Jabbar Editted
                print(os.path.join(cfg.AVA.FRAME_DIR,row[3]))
                ###
                if video_name not in video_name_to_idx:
                    idx = len(video_name_to_idx)
                    video_name_to_idx[video_name] = idx
                    video_idx_to_name.append(video_name)

                data_key = video_name_to_idx[video_name]
                image_paths[data_key].append(
                    os.path.join(cfg.AVA.FRAME_DIR, row[3])
                )
```
However, I still do not know how to fix it
