### ISSUE TITLE
_pickle.UnpicklingError: A load persistent id instruction was encountered, but no persistent_load function was specified.

### ISSUE THREAD

**Issue by liyanzu0926** [facebookresearch/SlowFast#622]
Thank you for your work！
I trained other datasets:  `AUTSL` , epoch=196 , top1_ err=0.4876 , but when I load my checkpoint file to test the accuracy, an error is reported：
> Traceback (most recent call last):
  File "/home/lyz/.conda/envs/torch10/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/yu1/lyz/code/SlowFast/slowfast/utils/multiprocessing.py", line 60, in run
    ret = func(cfg)
  File "/yu1/lyz/code/SlowFast/tools/test_net.py", line 215, in test
    cu.load_test_checkpoint(cfg, model)
  File "/yu1/lyz/code/SlowFast/slowfast/utils/checkpoint.py", line 683, in load_test_checkpoint
    load_checkpoint(
  File "/yu1/lyz/code/SlowFast/slowfast/utils/checkpoint.py", line 231, in load_checkpoint
    caffe2_checkpoint = pickle.load(f, encoding="latin1")
_pickle.UnpicklingError: A load persistent id instruction was encountered,
but no persistent_load function was specified.

My yaml file is as follows:
> TRAIN:
  ENABLE: False
  DATASET: autsl
  BATCH_SIZE: 64
  EVAL_PERIOD: 10
  CHECKPOINT_PERIOD: 1
  AUTO_RESUME: True
  CHECKPOINT_TYPE: caffe2
  CHECKPOINT_FILE_PATH: /yu1/lyz/code/SlowFast/configs/AUTSL/SLOWFAST_8x8_R50.pkl
DATA:
  NUM_FRAMES: 16
  SAMPLING_RATE: 2
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 256
  INPUT_CHANNEL_NUM: [3, 3]
  PATH_TO_DATA_DIR: /yu1/lww/code/SlowFast/data/Autsl
  DECODING_BACKEND: pyav
SLOWFAST:
  ALPHA: 4
  BETA_INV: 8
  FUSION_CONV_CHANNEL_RATIO: 2
  FUSION_KERNEL_SZ: 7
RESNET:
  ZERO_INIT_FINAL_BN: True
  WIDTH_PER_GROUP: 64
  NUM_GROUPS: 1
  DEPTH: 50
  TRANS_FUNC: bottleneck_transform
  STRIDE_1X1: False
  NUM_BLOCK_TEMP_KERNEL: [[3, 3], [4, 4], [6, 6], [3, 3]]
  SPATIAL_STRIDES: [[1, 1], [2, 2], [2, 2], [2, 2]]
  SPATIAL_DILATIONS: [[1, 1], [1, 1], [1, 1], [1, 1]]
NONLOCAL:
  LOCATION: [[[], []], [[], []], [[], []], [[], []]]
  GROUP: [[1, 1], [1, 1], [1, 1], [1, 1]]
  INSTANTIATION: dot_product
BN:
  USE_PRECISE_STATS: True
  NUM_BATCHES_PRECISE: 200
SOLVER:
  BASE_LR: 0.1
  LR_POLICY: cosine
  MAX_EPOCH: 196
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-4
  WARMUP_EPOCHS: 34.0
  WARMUP_START_LR: 0.01
  OPTIMIZING_METHOD: sgd
MODEL:
  NUM_CLASSES: 226
  ARCH: slowfast
  MODEL_NAME: SlowFast
  LOSS_FUNC: cross_entropy
  DROPOUT_RATE: 0.5
TEST:
  ENABLE: True
  DATASET: autsl
  BATCH_SIZE: 64
  CHECKPOINT_TYPE: caffe2
  CHECKPOINT_FILE_PATH: /yu1/lyz/code/SlowFast/checkpoints/checkpoint_epoch_00196.pyth
DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True
TENSORBOARD:
  ENABLE: True
NUM_GPUS: 8
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: .

**Comment by liyanzu0926** [comment]
When I set `TEST.CHECKPOINT_TYPE: pytorch` ,  the accuracy is very low.
`logging.py:   99: json_stats: {"split": "test_final", "top1_acc": "1.07", "top5_acc": "3.31"}`
