### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by nip6** [facebookresearch/SlowFast#645]
I encountered an error while running my code using the training and validation sets provided by the official dataset. Specifically, I used the first video in each set as the training and validation data, respectively. However, the error persists even when I reduced the dataset to a single row that has sufficient 8 columns for validation. I'm not sure what to do now and would appreciate any guidance.

Traceback (most recent call last):
  File "C:\Users\14621\Desktop\slowfast (2)\slowfast\tools\run_net.py", line 53, in <module>
    main()
  File "C:\Users\14621\Desktop\slowfast (2)\slowfast\tools\run_net.py", line 28, in main
    launch_job(cfg=cfg, init_method=args.init_method, func=train)
  File "c:\users\14621\desktop\slowfast (2)\slowfast\slowfast\utils\misc.py", line 430, in launch_job
    func(cfg=cfg)
  File "C:\Users\14621\Desktop\slowfast (2)\slowfast\tools\train_net.py", line 596, in train
    train_loader = loader.construct_loader(cfg, "train")
  File "c:\users\14621\desktop\slowfast (2)\slowfast\slowfast\datasets\loader.py", line 114, in construct_loader
    dataset = build_dataset(dataset_name, cfg, split)
  File "c:\users\14621\desktop\slowfast (2)\slowfast\slowfast\datasets\build.py", line 31, in build_dataset
    return DATASET_REGISTRY.get(name)(cfg, split)
  File "c:\users\14621\desktop\slowfast (2)\slowfast\slowfast\datasets\ava_dataset.py", line 47, in __init__
    self._load_data(cfg)
  File "c:\users\14621\desktop\slowfast (2)\slowfast\slowfast\datasets\ava_dataset.py", line 63, in _load_data
    boxes_and_labels = ava_helper.load_boxes_and_labels(
  File "c:\users\14621\desktop\slowfast (2)\slowfast\slowfast\datasets\ava_helper.py", line 100, in load_boxes_and_labels
    all_boxes, count, unique_box_count = parse_bboxes_file(
  File "c:\users\14621\desktop\slowfast (2)\slowfast\slowfast\datasets\ava_helper.py", line 204, in parse_bboxes_file
    score = float(row[7])
IndexError: list index out of range

TRAIN:
  ENABLE: True
  DATASET: ava
  BATCH_SIZE: 64
  EVAL_PERIOD: 5
  CHECKPOINT_PERIOD: 1
  AUTO_RESUME: True
  CHECKPOINT_FILE_PATH: C://Users//14621//Desktop//slowfast (2)//slowfast//configs//AVA//SLOWFAST_32x2_R101_50_50.pkl
  CHECKPOINT_TYPE: "caffe2"
DATA:
  NUM_FRAMES: 32
  SAMPLING_RATE: 2
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 224
  INPUT_CHANNEL_NUM: [3, 3]
  PATH_TO_DATA_DIR: C://Users//14621//Desktop//slowfast (2)//INPUT_VIDEO//ava
DETECTION:
  ENABLE: True
  ALIGNED: True
AVA:
  FRAME_DIR: 'C://Users//14621//Desktop//slowfast (2)//INPUT_VIDEO//ava//frames'
  FRAME_LIST_DIR: 'C://Users//14621//Desktop//slowfast (2)//INPUT_VIDEO//ava//frame_lists'
  ANNOTATION_DIR: 'C:\Users\14621\Desktop\slowfast (2)\INPUT_VIDEO\ava\annotations\ava_annotations'
  DETECTION_SCORE_THRESH: 0.8
  TRAIN_PREDICT_BOX_LISTS: [
    "ava_train_v2.2.csv",
    "person_box_67091280_iou75//ava_detection_train_boxes_and_labels_include_negative_v2.2.csv",
  ]
  TEST_PREDICT_BOX_LISTS: [
    "person_box_67091280_iou75//ava_detection_val_boxes_and_labels.csv"
  ]
SLOWFAST:
  ALPHA: 4
  BETA_INV: 8
  FUSION_CONV_CHANNEL_RATIO: 2
  FUSION_KERNEL_SZ: 7
RESNET:
  ZERO_INIT_FINAL_BN: True
  WIDTH_PER_GROUP: 64
  NUM_GROUPS: 1
  DEPTH: 50
  TRANS_FUNC: bottleneck_transform
  STRIDE_1X1: False
  NUM_BLOCK_TEMP_KERNEL: [[3, 3], [4, 4], [6, 6], [3, 3]]
  SPATIAL_DILATIONS: [[1, 1], [1, 1], [1, 1], [2, 2]]
  SPATIAL_STRIDES: [[1, 1], [2, 2], [2, 2], [1, 1]]
NONLOCAL:
  LOCATION: [[[], []], [[], []], [[], []], [[], []]]
  GROUP: [[1, 1], [1, 1], [1, 1], [1, 1]]
  INSTANTIATION: dot_product
  POOL: [[[1, 2, 2], [1, 2, 2]], [[1, 2, 2], [1, 2, 2]], [[1, 2, 2], [1, 2, 2]], [[1, 2, 2], [1, 2, 2]]]
BN:
  USE_PRECISE_STATS: False
  NUM_BATCHES_PRECISE: 200
SOLVER:
  BASE_LR: 0.1
  LR_POLICY: steps_with_relative_lrs
  STEPS: [0, 10, 15, 20]
  LRS: [1, 0.1, 0.01, 0.001]
  MAX_EPOCH: 20
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-7
  WARMUP_EPOCHS: 5.0
  WARMUP_START_LR: 0.000125
  OPTIMIZING_METHOD: sgd
MODEL:
  NUM_CLASSES: 80
  ARCH: slowfast
  MODEL_NAME: SlowFast
  LOSS_FUNC: bce
  DROPOUT_RATE: 0.5
  HEAD_ACT: sigmoid
TEST:
  ENABLE: False
  DATASET: ava
  BATCH_SIZE: 8
DATA_LOADER:
  NUM_WORKERS: 2
  PIN_MEMORY: True
NUM_GPUS: 1
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: .

**Comment by XDU-fw** [comment]
I have the same question. Have you deal with it?

**Comment by Helianthusss** [comment]
I have the same question. 
![image](https://github.com/facebookresearch/SlowFast/assets/75102477/d48b44e3-6807-4cbc-8af2-ff6dfa5e1af5)
Help me solution?

**Comment by XDU-fw** [comment]
Maybe you can try to delete the blank line from '.csv' files.
