### ISSUE TITLE
TypeError: init_distributed_training() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by hefengh** [facebookresearch/SlowFast#651]
When I'm training with ava dataset, this happens, how can I modify the code to make him run completely?The specific situation is as follows：
Traceback (most recent call last):
  File "tools/run_net.py", line 52, in <module>
    main()
  File "tools/run_net.py", line 27, in main
    launch_job(cfg=cfg, init_method=args.init_method, func=train)
  File "/root/SlowFast/slowfast/utils/misc.py", line 430, in launch_job
    func(cfg=cfg)
  File "/root/SlowFast/tools/train_net.py", line 520, in train
    du.init_distributed_training(cfg)
  File "/root/SlowFast/slowfast/utils/distributed.py", line 23, in init_distributed_training
    _init_distributed_training = init_distributed_training(cfg.NUM_GPUS, cfg.SHARD_ID)
TypeError: init_distributed_training() takes 1 positional argument but 2 were given

**Comment by Eurususu** [comment]
I just change 
return _init_distributed_training(cfg.NUM_GPUS, cfg.SHARD_ID)
to
return _init_distributed_training(cfg)
No error
