### ISSUE TITLE
How to solve it： cannot import name 'cat_all_gather' from 'pytorchvideo.layers.distributed' 

### ISSUE THREAD

**Issue by xqc-qc** [facebookresearch/SlowFast#663]
Traceback (most recent call last):
  File "tools/run_net.py", line 6, in <module>
    from slowfast.utils.misc import launch_job
  File "/root/slowfast/slowfast/utils/misc.py", line 19, in <module>
    import slowfast.utils.logging as logging
  File "/root/slowfast/slowfast/utils/logging.py", line 15, in <module>
    import slowfast.utils.distributed as du
  File "/root/slowfast/slowfast/utils/distributed.py", line 12, in <module>
    from pytorchvideo.layers.distributed import (  # noqa
ImportError: cannot import name 'cat_all_gather' from 'pytorchvideo.layers.distributed' (/root/miniconda3/envs/cnslowfast/lib/python3.8/site-packages/pytorchvideo/layers/distributed.py)

**Comment by 9bxlue** [comment]
how to solve?Question is same!

**Comment by wjw0905** [comment]
same.....

**Comment by wjw0905** [comment]
i solve this problem
1. clone this project : git clone https://github.com/facebookresearch/pytorchvideo.git
2. cd into this project:cd pytorchvideo
3. input following words in terminal : pip install -e /share/program/wjw/pytorchvideo(replace this with your project address)

**Comment by AlphaGoooo** [comment]
> i solve this problem
> 
> 1. clone this project : git clone https://github.com/facebookresearch/pytorchvideo.git
> 2. cd into this project:cd pytorchvideo
> 3. input following words in terminal : pip install -e /share/program/wjw/pytorchvideo(replace this with your project address)

thanks a lot, my problem is successfully solved.

**Comment by xqc-qc** [comment]
> i solve this problem
> 
> 1. clone this project : git clone https://github.com/facebookresearch/pytorchvideo.git
> 2. cd into this project:cd pytorchvideo
> 3. input following words in terminal : pip install -e /share/program/wjw/pytorchvideo(replace this with your project address)

Thank you, do you know how to make the annatation file of the ava dataset? The coordinates in this (ava_detection_val_boxes_and_labels.csv) don’t know how to do it. Have you tried it?

**Comment by drrashijaiswal** [comment]
> i solve this problem
> 
> 1. clone this project : git clone https://github.com/facebookresearch/pytorchvideo.git
> 2. cd into this project:cd pytorchvideo
> 3. input following words in terminal : pip install -e /share/program/wjw/pytorchvideo(replace this with your project address)

not solved yet
