### ISSUE TITLE
Mvitv2 dataset

### ISSUE THREAD

**Issue by xqc-qc** [facebookresearch/SlowFast#688]
What is the format of the MVITV2 dataset and how to make it?

**Comment by xqc-qc** [comment]
Traceback (most recent call last):
  File "tools/run_net.py", line 52, in <module>
    main()
  File "tools/run_net.py", line 27, in main
    launch_job(cfg=cfg, init_method=args.init_method, func=train)
  File "/root/SlowFast/slowfast/utils/misc.py", line 430, in launch_job
    func(cfg=cfg)
  File "/root/SlowFast/tools/train_net.py", line 555, in train
    checkpoint_epoch = cu.load_checkpoint(
  File "/root/SlowFast/slowfast/utils/checkpoint.py", line 558, in load_checkpoint
    optimizer.load_state_dict(checkpoint["optimizer_state"])
  File "/root/miniconda3/envs/slowfast/lib/python3.8/site-packages/torch/optim/optimizer.py", line 146, in load_state_dict
    raise ValueError("loaded state dict contains a parameter group "
ValueError: loaded state dict contains a parameter group that doesn't match the size of optimizer's group
![image](https://github.com/facebookresearch/SlowFast/assets/128236906/4ea834b5-ae17-41d3-ae9e-ce8082f849e0)

![image](https://github.com/facebookresearch/SlowFast/assets/128236906/e612fed1-e020-4f95-a373-9ab643c6d866)
What I did was K400 data format, why is it wrong?

**Comment by alpargun** [comment]
Can you share your experiment config file?

You can refer to provided MViTv2 experiment config files:

- [MViTv2 supervised training on Kinetics](https://github.com/facebookresearch/SlowFast/blob/main/configs/Kinetics/MVITv2_L_40x3_test.yaml)
- [MViTv2 masked self-supervised training on Kinetics](https://github.com/facebookresearch/SlowFast/blob/main/configs/masked_ssl/k400_MVITv2_S_16x4_MaskFeat_PT.yaml)

However, looking at your error, it seems like the problem is due to loading the model and the checkpoint, so could be due to the head network or incorrect config file. Providing your config file will also help track the error.

**Comment by xqc-qc** [comment]
> Can you share your experiment config file?
> 
> You can refer to provided MViTv2 experiment config files:
> 
> * [MViTv2 supervised training on Kinetics](https://github.com/facebookresearch/SlowFast/blob/main/configs/Kinetics/MVITv2_L_40x3_test.yaml)
> * [MViTv2 masked self-supervised training on Kinetics](https://github.com/facebookresearch/SlowFast/blob/main/configs/masked_ssl/k400_MVITv2_S_16x4_MaskFeat_PT.yaml)
> 
> However, looking at your error, it seems like the problem is due to loading the model and the checkpoint, so could be due to the head network or incorrect config file. Providing your config file will also help track the error.
[config.txt](https://github.com/facebookresearch/SlowFast/files/14413636/config.txt)

**Comment by alpargun** [comment]
@xqc-qc,
> > [config.txt](https://github.com/facebookresearch/SlowFast/files/14413636/config.txt)

Looking at your config file, I understand that you would like to train on AVA dataset. 

<img width="146" alt="image" src="https://github.com/facebookresearch/SlowFast/assets/52760747/59005664-1d1d-4395-b601-18640c22a93f">

Your NUM_CLASSES is 7, but the config file for AVA in [configs/AVA/SLOWFAST_32x2_R50_SHORT.yaml](https://github.com/facebookresearch/SlowFast/blob/main/configs/AVA/SLOWFAST_32x2_R50_SHORT.yaml) has NUM_CLASSES: 80

<img width="188" alt="image" src="https://github.com/facebookresearch/SlowFast/assets/52760747/faa8b9df-812c-4370-977b-c1ab0042eac4">

So, the model checkpoint you downloaded should have 80 output neurons but here you are initializing a model with 7 output neurons. You need to set NUM_CLASSES as it appears in the original [config file](https://github.com/facebookresearch/SlowFast/blob/main/configs/AVA/SLOWFAST_32x2_R50_SHORT.yaml) to restore the checkpoint and the state dictionary successfully.

If you did that on purpose, i.e., you want 7 outputs for your application, so you want to train a new last layer (linear probing), then you can check out fine-tuning in SlowFast.

**Comment by xqc-qc** [comment]
> @xqc-qc,
> 
> > > [config.txt](https://github.com/facebookresearch/SlowFast/files/14413636/config.txt)
> 
> Looking at your config file, I understand that you would like to train on AVA dataset.
> 
> <img alt="image" width="146" src="https://private-user-images.githubusercontent.com/52760747/308560888-59005664-1d1d-4395-b601-18640c22a93f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxNzE3MTksIm5iZiI6MTcwOTE3MTQxOSwicGF0aCI6Ii81Mjc2MDc0Ny8zMDg1NjA4ODgtNTkwMDU2NjQtMWQxZC00Mzk1LWI2MDEtMTg2NDBjMjJhOTNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI5VDAxNTAxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIxZTU2NzNiZTgyYWI3ZDI4YmNkZjE2YjFlNDkxODlkMjlhZjc5NjFhODZjZGE4NmMyY2JjZTY5MzgwMGQxOWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.j4FBsh2U9WLPDVGv3yFAatq6BXh9ZUS7_G3TetbI8_4">
> Your NUM_CLASSES is 7, but the config file for AVA in [configs/AVA/SLOWFAST_32x2_R50_SHORT.yaml](https://github.com/facebookresearch/SlowFast/blob/main/configs/AVA/SLOWFAST_32x2_R50_SHORT.yaml) has NUM_CLASSES: 80
> 
> <img alt="image" width="188" src="https://private-user-images.githubusercontent.com/52760747/308561519-faa8b9df-812c-4370-977b-c1ab0042eac4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxNzE3MTksIm5iZiI6MTcwOTE3MTQxOSwicGF0aCI6Ii81Mjc2MDc0Ny8zMDg1NjE1MTktZmFhOGI5ZGYtODEyYy00MzcwLTk3N2ItYzFhYjAwNDJlYWM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI5VDAxNTAxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhNTQwY2Y4MmZhOGYwMDA2N2YxNmIxM2RhMDI2YzgxMWEwOTU1YTZiOTE1YjA2NWVlMzg1YjcwYWViZGE1YmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0WX_MUlWxtbpV6aH5O-m7o8xxZkFghOqKAVm48vHAD0">
> So, the model checkpoint you downloaded should have 80 output neurons but here you are initializing a model with 7 output neurons. You need to set NUM_CLASSES as it appears in the original [config file](https://github.com/facebookresearch/SlowFast/blob/main/configs/AVA/SLOWFAST_32x2_R50_SHORT.yaml) to restore the checkpoint and the state dictionary successfully.
> 
> If you did that on purpose, i.e., you want 7 outputs for your application, so you want to train a new last layer (linear probing), then you can check out fine-tuning in SlowFast.

Thank you very much, thank you for your answer！
