### ISSUE TITLE
AttributeError: module 'torch' has no attribute 'compiler'

### ISSUE THREAD

**Issue by Cheng-ZY** [facebookresearch/SlowFast#709]
Has anyone encountered this problem？I am very certain that I have installed Torch
Traceback (most recent call last):
  File "/root/SlowFast/slowfast/tools/run_net.py", line 6, in <module>
    from slowfast.utils.misc import launch_job
  File "/root/SlowFast/slowfast/slowfast/utils/misc.py", line 21, in <module>
    from slowfast.datasets.utils import pack_pathway_output
  File "/root/SlowFast/slowfast/slowfast/datasets/__init__.py", line 7, in <module>
    from .imagenet import Imagenet  # noqa
  File "/root/SlowFast/slowfast/slowfast/datasets/imagenet.py", line 15, in <module>
    from slowfast.models.utils import calc_mvit_feature_geometry
  File "/root/SlowFast/slowfast/slowfast/models/__init__.py", line 5, in <module>
    from .contrastive import ContrastiveModel  # noqa
  File "/root/SlowFast/slowfast/slowfast/models/contrastive.py", line 13, in <module>
    from slowfast.models.video_model_builder import X3D, MViT, ResNet, SlowFast
  File "/root/SlowFast/slowfast/slowfast/models/video_model_builder.py", line 26, in <module>
    from . import head_helper, operators, resnet_helper, stem_helper  # noqa
  File "/root/SlowFast/slowfast/slowfast/models/head_helper.py", line 9, in <module>
    from detectron2.layers import ROIAlign
  File "/root/SlowFast/detectron2_repo/detectron2/layers/__init__.py", line 5, in <module>
    from .nms import batched_nms, batched_nms_rotated, nms, nms_rotated
  File "/root/SlowFast/detectron2_repo/detectron2/layers/nms.py", line 25, in <module>
    @torch.compiler.disable
AttributeError: module 'torch' has no attribute 'compiler'

**Comment by 3210448723** [comment]
https://github.com/facebookresearch/detectron2/issues/5268#issuecomment-2075633467
