### ISSUE TITLE
ValueError: invalid literal for int() with base 10: '   How can I fix it？

### ISSUE THREAD

**Issue by TPF0628** [facebookresearch/SlowFast#714]
Traceback (most recent call last): 
  File "D:\Downloads\slowfast\slowfast\tools\run_net.py", line 50, in <module>
    main()
  File "D:\Downloads\slowfast\slowfast\tools\run_net.py", line 26, in main
    launch_job(cfg=cfg, init_method=args.init_method, func=train)
  File "d:\downloads\slowfast\slowfast\slowfast\utils\misc.py", line 421, in launch_job
    func(cfg=cfg)
  File "D:\Downloads\slowfast\slowfast\tools\train_net.py", line 579, in train
    train_loader = loader.construct_loader(cfg, "train")
  File "d:\downloads\slowfast\slowfast\slowfast\datasets\loader.py", line 115, in construct_loader
    dataset = build_dataset(dataset_name, cfg, split)
  File "d:\downloads\slowfast\slowfast\slowfast\datasets\build.py", line 31, in build_dataset
    return DATASET_REGISTRY.get(name)(cfg, split)
  File "d:\downloads\slowfast\slowfast\slowfast\datasets\ava_dataset.py", line 50, in __init__
    self._load_data(cfg)
  File "d:\downloads\slowfast\slowfast\slowfast\datasets\ava_dataset.py", line 66, in _load_data
    boxes_and_labels = ava_helper.load_boxes_and_labels(cfg, mode=self._split)
  File "d:\downloads\slowfast\slowfast\slowfast\datasets\ava_helper.py", line 93, in load_boxes_and_labels
    all_boxes, count, unique_box_count = parse_bboxes_file(
  File "d:\downloads\slowfast\slowfast\slowfast\datasets\ava_helper.py", line 194, in parse_bboxes_file
    video_name, frame_sec = row[0], int(row[1])
ValueError: invalid literal for int() with base 10: '

**Comment by pepper725** [comment]
have you solved this problem?
