### ISSUE TITLE
assert len(boxes_and_labels) == len(self._image_paths)

### ISSUE THREAD

**Issue by wangweiweiweiweiwei** [facebookresearch/SlowFast#738]
Traceback (most recent call last):
  File "run_net.py", line 50, in <module>
    main()
  File "run_net.py", line 26, in main
    launch_job(cfg=cfg, init_method=args.init_method, func=train)
  File "/home/AVA/SlowFast-main/slowfast/utils/misc.py", line 421, in launch_job
    func(cfg=cfg)
  File "/home/AVA/SlowFast-main/tools/train_net.py", line 579, in train
    train_loader = loader.construct_loader(cfg, "train")
  File "/home/AVA/SlowFast-main/slowfast/datasets/loader.py", line 115, in construct_loader
    dataset = build_dataset(dataset_name, cfg, split)
  File "/home/AVA/SlowFast-main/slowfast/datasets/build.py", line 31, in build_dataset
    return DATASET_REGISTRY.get(name)(cfg, split)
  File "/home/AVA/SlowFast-main/slowfast/datasets/ava_dataset.py", line 50, in __init__
    self._load_data(cfg)
  File "/home/AVA/SlowFast-main/slowfast/datasets/ava_dataset.py", line 68, in _load_data
    assert len(boxes_and_labels) == len(self._image_paths)
AssertionError

**Comment by wangweiweiweiweiwei** [comment]
len(boxes_and_labels) 加载的不是一秒一帧的数据， len(self._image_paths)加载的是一秒30帧的数据，为什么在这里判断俩数据相等？

**Comment by hongqiwei123** [comment]
你好，我也遇到了相同的问题，我是在加载val数据集的时候遇到的，请问你解决了吗
