### ISSUE TITLE
undefined symbol: cudaSetupArgument

### ISSUE THREAD

**Issue by ruyiweicas** [facebookresearch/SlowFast#75]
`(ruyiwei) [yiwei.ru@localhost Slowfast]$ python tools/test_net.py
Traceback (most recent call last):
  File "tools/test_net.py", line 14, in <module>
    from slowfast.models import model_builder
  File "/home/yiwei.ru/Code/Slowfast/slowfast/models/model_builder.py", line 8, in <module>
    from slowfast.models.video_model_builder import ResNetModel, SlowFastModel
  File "/home/yiwei.ru/Code/Slowfast/slowfast/models/video_model_builder.py", line 10, in <module>
    from slowfast.models import head_helper, resnet_helper, stem_helper
  File "/home/yiwei.ru/Code/Slowfast/slowfast/models/head_helper.py", line 8, in <module>
    from detectron2.layers import ROIAlign
  File "/home/yiwei.ru/Code/Slowfast/detectron2_repo/detectron2/layers/__init__.py", line 3, in <module>
    from .deform_conv import DeformConv, ModulatedDeformConv
  File "/home/yiwei.ru/Code/Slowfast/detectron2_repo/detectron2/layers/deform_conv.py", line 10, in <module>
    from detectron2 import _C
ImportError: /home/yiwei.ru/Code/Slowfast/detectron2_repo/detectron2/_C.cpython-37m-x86_64-linux-gnu.so: undefined symbol: cudaSetupArgument`

**Comment by takatosp1** [comment]
Hi, thanks for using the codebase!
Seems this is because one the the dependency [Detectron2](https://github.com/facebookresearch/detectron2/tree/master/detectron2) is not properly installed, you may found a lot of useful comments from the [asked question](https://github.com/facebookresearch/detectron2/issues/567). 
I feel it might related to your nvcc and pytorch cuda versions.
