### ISSUE TITLE
metada["boxes"].size(1) vs rois.size(1)

### ISSUE THREAD

**Issue by anhminh3105** [facebookresearch/SlowFast#81]
Hi @takatosp1 .

I am receiving this AssertionError when trying to feed tensor of boxes from detectron2 object detector to SlowFastModel.
```
....
[WARNING: compat.py:  110]: Config '/media/am/DATA/Projects/detectron2/detectron2/model_zoo/configs/COCO-Detection/faster_rcnn_R_50_FPN_3x.yaml' has no VERSION. Assuming it to be compatible with latest v2.
[INFO: checkpoint.py:   97]: Loading checkpoint from detectron2://COCO-Detection/faster_rcnn_R_50_FPN_3x/137849458/model_final_280758.pkl
[INFO: file_io.py:  407]: URL https://dl.fbaipublicfiles.com/detectron2/COCO-Detection/faster_rcnn_R_50_FPN_3x/137849458/model_final_280758.pkl cached in /home/am/.torch/fvcore_cache/detectron2/COCO-Detection/faster_rcnn_R_50_FPN_3x/137849458/model_final_280758.pkl
[INFO: detection_checkpoint.py:   32]: Reading a file from 'Detectron2 Model Zoo'
[INFO: demo_net.py:  151]: outputs["instances"]._fields.tensor[person_class_mask].shape=torch.Size([1, 4])
[INFO: demo_net.py:  156]: cv2_transoform_scaled_boxes.shape=torch.Size([1, 4])
[INFO: demo_net.py:  157]: cv2_transoform_scaled_boxes.size()=torch.Size([1, 4])
[INFO: demo_net.py:  173]: fast_pathway.shape=torch.Size([1, 3, 32, 256, 341])
[INFO: demo_net.py:  179]: slow_pathway.shape=torch.Size([1, 3, 8, 256, 341])
Traceback (most recent call last):
  File "tools/run_net.py", line 142, in <module>
    main()
  File "tools/run_net.py", line 138, in main
    func(cfg=cfg)
  File "/home/am/Workspace/SlowFast/tools/demo_net.py", line 191, in demo
    preds = model(inputs, boxes)
  File "/home/am/.conda/envs/slowfast/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/am/Workspace/SlowFast/slowfast/models/video_model_builder.py", line 372, in forward
    x = self.head(x, bboxes)
  File "/home/am/.conda/envs/slowfast/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/am/Workspace/SlowFast/slowfast/models/head_helper.py", line 115, in forward
    out = roi_align(out, bboxes)
  File "/home/am/.conda/envs/slowfast/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/am/DATA/Projects/detectron2/detectron2/layers/roi_align.py", line 93, in forward
    assert rois.dim() == 2 and rois.size(1) == 5
AssertionError
```
based on the traceback above, roi_align requires rois.shape=[num_boxes, 5] with description of rois as `Bx5 boxes. First column is the index into N. The other 4 columns are xyxy.`

However, I was looking intensively the behaviour of your source code in class Ava()  in ava_dataset.py, metadata["boxes"] seems to have shape [n, 4] based on how  _images_and_boxes_preprocessing_cv2() is doing. 

Also in train_net.py and test_net.py, the boxes are directly passed to the model forward function:
```
            # Compute the predictions.
            preds = model(inputs, meta["boxes"])
```
which is then passed to ResNetRoIHead forward function, which in turn, passed to roi_align of detectron2.

Can you help shed some light on this?

Thanks in advance.

Best regards
Minh

**Comment by takatosp1** [comment]
Hi, @anhminh3105 thanks for playing with AVA in PySlowFast!
The first column of the index is prepared in the loader.py, which is shared across different data loaders, you might found this helpful:
https://github.com/facebookresearch/SlowFast/blob/master/slowfast/datasets/loader.py#L35-L41
Feel free to add any follow up questions if there is any :P
