### ISSUE TITLE
CUDA and  CUDNN version 

### ISSUE THREAD

**Issue by gooners1886** [facebookresearch/SlowFast#9]
what is the corrent verion to match this slowfast code on CentOS 7.2?

Traceback (most recent call last):
  File "/root/software_install/anaconda2/envs/pytorch1/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/root/code/sf/sf1/slowfast/utils/multiprocessing.py", line 49, in run
    torch.cuda.set_device(local_rank)
  File "/root/software_install/anaconda2/envs/pytorch1/lib/python3.6/site-packages/torch/cuda/__init__.py", line 300, in set_device
    torch._C._cuda_setDevice(device)
  File "/root/software_install/anaconda2/envs/pytorch1/lib/python3.6/site-packages/torch/cuda/__init__.py", line 192, in _lazy_init
    _check_driver()
  File "/root/software_install/anaconda2/envs/pytorch1/lib/python3.6/site-packages/torch/cuda/__init__.py", line 111, in _check_driver
    of the CUDA driver.""".format(str(torch._C._cuda_getDriverVersion())))
AssertionError: 
The NVIDIA driver on your system is too old (found version 10000).
Please update your GPU driver by downloading and installing a new
version from the URL: http://www.nvidia.com/Download/index.aspx
Alternatively, go to: https://pytorch.org to install
a PyTorch version that has been compiled with your version
of the CUDA driver.

**Comment by takatosp1** [comment]
Hi,
Thanks for using the codebase! The slowfast codebase can be used with most of the cuda versions. The issue you found looks to be a known issue for pytorch installation, which is not related to our codebase, you can found more details from here:
https://github.com/pytorch/pytorch/issues/27738

Of course I’m happy to help you solve your pytorch installation issue but you might need to provide more details about your env if you want further help from us: 
What is your GCC version, your cuda version and your pytorch version.
