### ISSUE TITLE
demo Error

### ISSUE THREAD

**Issue by gtgtgt1117** [facebookresearch/SlowFast#94]
hI
python tools/run_net.py --cfg configs/Kinetics/c2/SLOWFAST_8x8_R50.yaml DATA.PATH_TO_DATA_DIR
当我运行这个的时候出现这个错误,可能是我下载的test.csv的问题,您能提供我一下吗?

Traceback (most recent call last):
  File "/home/vcaadmin/miniconda3/envs/slowfast/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/data/gao/slowfast/slowfast/utils/multiprocessing.py", line 50, in run
    func(cfg)
  File "/data/gao/sf/SlowFast-master/tools/test_net.py", line 160, in test
    test_loader = loader.construct_loader(cfg, "test")
  File "/data/gao/slowfast/slowfast/datasets/loader.py", line 80, in construct_loader
    dataset = build_dataset(dataset_name, cfg, split)
  File "/data/gao/slowfast/slowfast/datasets/build.py", line 32, in build_dataset
    return DATASET_REGISTRY.get(name)(cfg, split)
  File "/data/gao/slowfast/slowfast/datasets/kinetics.py", line 74, in __init__
    self._construct_loader()
  File "/data/gao/slowfast/slowfast/datasets/kinetics.py", line 92, in _construct_loader
    assert len(path_label.split()) == 2
AssertionError

thanks a lot!!

**Comment by chongruo** [comment]
it's probably because the path contains extra spaces.

**Comment by gtgtgt1117** [comment]
> it's probably because the path contains extra spaces.

路径应该是没有问题的.我的csv文件如下:

label | youtube_id | time_start | time_end | split
-- | -- | -- | -- | --
shaking hands | --0BJ-j7tg8 | 0 | 10 | test

报错那部分的代码如下slowfast/slowfast/datasets/kinetics.py:
with open(path_to_file, "r") as f:
            for clip_idx, path_label in enumerate(f.read().splitlines()):
                assert len(path_label.split()) == 2
                path, label = path_label.split()
                for idx in range(self._num_clips):
                    self._path_to_videos.append(
                        os.path.join(self.cfg.DATA.PATH_PREFIX, path)
                    )
                    self._labels.append(int(label))
没有很理解,谢谢您的回答

**Comment by chongruo** [comment]
You may need to follow the [same format](https://github.com/facebookresearch/SlowFast/blob/master/slowfast/datasets/DATASET.md) if you train on a kinetics-like dataset. Each line in the csv file only contains path and label.

**Comment by gtgtgt1117** [comment]
> You may need to follow the [same format](https://github.com/facebookresearch/SlowFast/blob/master/slowfast/datasets/DATASET.md) if you train on a kinetics-like dataset. Each line in the csv file only contains path and label.

thanks 我明白了

**Comment by ruilongzhang** [comment]
> You may need to follow the [same format](https://github.com/facebookresearch/SlowFast/blob/master/slowfast/datasets/DATASET.md) if you train on a kinetics-like dataset. Each line in the csv file only contains path and label.



> > it's probably because the path contains extra spaces.
> 
> 路径应该是没有问题的.我的csv文件如下:
> 
> label	youtube_id	time_start	time_end	split
> shaking hands	--0BJ-j7tg8	0	10	test
> 报错那部分的代码如下slowfast/slowfast/datasets/kinetics.py:
> with open(path_to_file, "r") as f:
> for clip_idx, path_label in enumerate(f.read().splitlines()):
> assert len(path_label.split()) == 2
> path, label = path_label.split()
> for idx in range(self._num_clips):
> self._path_to_videos.append(
> os.path.join(self.cfg.DATA.PATH_PREFIX, path)
> )
> self._labels.append(int(label))
> 没有很理解,谢谢您的回答



> You may need to follow the [same format](https://github.com/facebookresearch/SlowFast/blob/master/slowfast/datasets/DATASET.md) if you train on a kinetics-like dataset. Each line in the csv file only contains path and label.

I  test with SLOWFAST_8x8_R50.yaml .  but result is  _top_max_k_valstensor([[  2, 236,  16, 140, 304]]), i do not konw the classesid map,  can you tell me ?  @chongruo

**Comment by ruilongzhang** [comment]
> hI
> python tools/run_net.py --cfg configs/Kinetics/c2/SLOWFAST_8x8_R50.yaml DATA.PATH_TO_DATA_DIR
> 当我运行这个的时候出现这个错误,可能是我下载的test.csv的问题,您能提供我一下吗?
> 
> Traceback (most recent call last):
> File "/home/vcaadmin/miniconda3/envs/slowfast/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
> fn(i, *args)
> File "/data/gao/slowfast/slowfast/utils/multiprocessing.py", line 50, in run
> func(cfg)
> File "/data/gao/sf/SlowFast-master/tools/test_net.py", line 160, in test
> test_loader = loader.construct_loader(cfg, "test")
> File "/data/gao/slowfast/slowfast/datasets/loader.py", line 80, in construct_loader
> dataset = build_dataset(dataset_name, cfg, split)
> File "/data/gao/slowfast/slowfast/datasets/build.py", line 32, in build_dataset
> return DATASET_REGISTRY.get(name)(cfg, split)
> File "/data/gao/slowfast/slowfast/datasets/kinetics.py", line 74, in **init**
> self._construct_loader()
> File "/data/gao/slowfast/slowfast/datasets/kinetics.py", line 92, in _construct_loader
> assert len(path_label.split()) == 2
> AssertionError
> 
> thanks a lot!!
您好，我目前也在学习这块， 能留个联系方式吗， 请教几个问题 @gtgtgt1117

**Comment by gtgtgt1117** [comment]
> > hI
> > python tools/run_net.py --cfg configs/Kinetics/c2/SLOWFAST_8x8_R50.yaml DATA.PATH_TO_DATA_DIR
> > 当我运行这个的时候出现这个错误,可能是我下载的test.csv的问题,您能提供我一下吗?
> > Traceback (most recent call last):
> > File "/home/vcaadmin/miniconda3/envs/slowfast/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
> > fn(i, *args)
> > File "/data/gao/slowfast/slowfast/utils/multiprocessing.py", line 50, in run
> > func(cfg)
> > File "/data/gao/sf/SlowFast-master/tools/test_net.py", line 160, in test
> > test_loader = loader.construct_loader(cfg, "test")
> > File "/data/gao/slowfast/slowfast/datasets/loader.py", line 80, in construct_loader
> > dataset = build_dataset(dataset_name, cfg, split)
> > File "/data/gao/slowfast/slowfast/datasets/build.py", line 32, in build_dataset
> > return DATASET_REGISTRY.get(name)(cfg, split)
> > File "/data/gao/slowfast/slowfast/datasets/kinetics.py", line 74, in **init**
> > self._construct_loader()
> > File "/data/gao/slowfast/slowfast/datasets/kinetics.py", line 92, in _construct_loader
> > assert len(path_label.split()) == 2
> > AssertionError
> > thanks a lot!!
> > 您好，我目前也在学习这块， 能留个联系方式吗， 请教几个问题 @gtgtgt1117

会的不是很多.共同学习吧.我的邮箱18801046982@163.com

**Comment by YuJiZhe** [comment]
> hI
> python tools/run_net.py --cfg configs/Kinetics/c2/SLOWFAST_8x8_R50.yaml DATA.PATH_TO_DATA_DIR
> 当我运行这个的时候出现这个错误,可能是我下载的test.csv的问题,您能提供我一下吗?
> 
> Traceback (most recent call last):
> File "/home/vcaadmin/miniconda3/envs/slowfast/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
> fn(i, *args)
> File "/data/gao/slowfast/slowfast/utils/multiprocessing.py", line 50, in run
> func(cfg)
> File "/data/gao/sf/SlowFast-master/tools/test_net.py", line 160, in test
> test_loader = loader.construct_loader(cfg, "test")
> File "/data/gao/slowfast/slowfast/datasets/loader.py", line 80, in construct_loader
> dataset = build_dataset(dataset_name, cfg, split)
> File "/data/gao/slowfast/slowfast/datasets/build.py", line 32, in build_dataset
> return DATASET_REGISTRY.get(name)(cfg, split)
> File "/data/gao/slowfast/slowfast/datasets/kinetics.py", line 74, in **init**
> self._construct_loader()
> File "/data/gao/slowfast/slowfast/datasets/kinetics.py", line 92, in _construct_loader
> assert len(path_label.split()) == 2
> AssertionError
> 
> thanks a lot!!

请问兄弟你用kinetics数据集进行demo测试过吗？

**Comment by gtgtgt1117** [comment]
是的
















在 2021-08-24 17:27:15，"GIGIGI" ***@***.***> 写道：

hI
python tools/run_net.py --cfg configs/Kinetics/c2/SLOWFAST_8x8_R50.yaml DATA.PATH_TO_DATA_DIR
当我运行这个的时候出现这个错误,可能是我下载的test.csv的问题,您能提供我一下吗?

Traceback (most recent call last):
File "/home/vcaadmin/miniconda3/envs/slowfast/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
fn(i, *args)
File "/data/gao/slowfast/slowfast/utils/multiprocessing.py", line 50, in run
func(cfg)
File "/data/gao/sf/SlowFast-master/tools/test_net.py", line 160, in test
test_loader = loader.construct_loader(cfg, "test")
File "/data/gao/slowfast/slowfast/datasets/loader.py", line 80, in construct_loader
dataset = build_dataset(dataset_name, cfg, split)
File "/data/gao/slowfast/slowfast/datasets/build.py", line 32, in build_dataset
return DATASET_REGISTRY.get(name)(cfg, split)
File "/data/gao/slowfast/slowfast/datasets/kinetics.py", line 74, in init
self._construct_loader()
File "/data/gao/slowfast/slowfast/datasets/kinetics.py", line 92, in _construct_loader
assert len(path_label.split()) == 2
AssertionError

thanks a lot!!

请问兄弟你用kinetics数据集进行demo测试过吗？

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by gtgtgt1117** [comment]
> Hi, how did you get the correct .csv file of Kinetics at last? I'm facing the same problem.

csv的格式错了吧？Each line in the csv file only contains path and label.
Example：
path_to_video_1 label_1
path_to_video_2 label_2
path_to_video_3 label_3
...
path_to_video_N label_N
